In [36]:
# Numpy axis and Keepdims Arguments 
import numpy as np 
# Vector case 1
"""

"""
print("\n============Vector============")
vec_a = np.arange(5)
print(f"vec_a shape : {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")
print(f"vec_a.sum() : {vec_a.sum()}")
print(f"np.sum(vec_a) : {np.sum(vec_a)}")

# Matrix case 1
print("\n============Matrix============")
mat_a = np.arange(6).reshape(2, -1)
print(f"mat_a shape : {mat_a.shape} ndim : {mat_a.ndim} \n {mat_a}")
print(f"mat_a.sum() : {mat_a.sum()}")
print(f"np.sum(mat_a) : {np.sum(mat_a)}")

total = 0 
for row in range(len(mat_a)):
    for col in range(len(mat_a[row])):
        total += mat_a[row][col] 
print(f"total : {total}")

# Tensor case 1
print("\n============Matrix============")
ten_a = np.arange(12).reshape(2, 3, 2)
print(f"ten_a shape : {ten_a.shape} ndim : {ten_a.ndim} \n {ten_a}")
print(f"ten_a.sum() : {ten_a.sum()}")
print(f"np.sum(ten_a) : {np.sum(ten_a)}")



============Vector============
vec_a shape : (5,) ndim : 1 
 [0 1 2 3 4]
vec_a.sum() : 10
np.sum(vec_a) : 10

============Matrix============
mat_a shape : (2, 3) ndim : 2 
 [[0 1 2]
 [3 4 5]]
mat_a.sum() : 15
np.sum(mat_a) : 15
total : 15

============Matrix============
ten_a shape : (2, 3, 2) ndim : 3 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
ten_a.sum() : 66
np.sum(ten_a) : 66


In [19]:
import numpy as np 

# Matrix case 2 
print("\n============Matrix============")
mat_b = np.arange(12).reshape(3, 4)
print(f"mat_b shpae : {mat_b.shape} ndim : {mat_b.ndim} \n {mat_b}")
print(f"mat_b axis=0 : \n{np.sum(mat_b, axis=0)}")
print(f"mat_b axis=1 : \n{np.sum(mat_b, axis=1)}")

# Tensor case 2
print("\n============Tensor============")
ten_b = np.arange(12).reshape(2, 3, 2)
print(f"ten_b shpae : {ten_b.shape} ndim : {ten_b.ndim} \n {ten_b}")
print(f"ten_b axis=0 : \n{np.sum(ten_b, axis=0)}")
print(f"ten_b axis=1 : \n{np.sum(ten_b, axis=1)}")


============Matrix============
mat_b shpae : (3, 4) ndim : 2 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat_b axis=0 : 
[12 15 18 21]
mat_b axis=1 : 
[ 6 22 38]

============Tensor============
ten_b shpae : (2, 3, 2) ndim : 3 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
ten_b axis=0 : 
[[ 6  8]
 [10 12]
 [14 16]]
ten_b axis=1 : 
[[ 6  9]
 [24 27]]


In [24]:
import numpy as np 

mat_c = np.arange(12).reshape(3, 4)

print(f"mat_c shpae : {mat_c.shape} ndim : {mat_c.ndim} \n {mat_c}")
row_mat_c = np.sum(mat_c, axis=0)
row_mat_c2 = mat_c.sum(axis=0)
col_mat_c = np.sum(mat_c, axis=1)
col_mat_c2 = mat_c.sum(axis=1)
print(f"row_mat_c axis=0 : \n{row_mat_c}")
print(f"col_mat_c axis=1 : \n{col_mat_c}")

mat_c shpae : (3, 4) ndim : 2 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row_mat_c axis=0 : 
[12 15 18 21]
col_mat_c axis=1 : 
[ 6 22 38]


In [32]:
import numpy as np 
mat_d = np.arange(12).reshape(3, 4)
print(f"mat_d shape : {mat_d.shape} ndim : {mat_d.ndim} \n{mat_d}")

sum_row_mat1 = mat_d.sum(axis=0, keepdims=True)
print("\n============Matrix | Keepdims=True ============")
print(f"sum_row_mat shape : {sum_row_mat1.shape} ndim : {sum_row_mat1.ndim} \n{sum_row_mat1}")

sum_row_mat2 = mat_d.sum(axis=0, keepdims=False)
print("\n============Matrix | Keepdims=False ============")
print(f"sum_row_mat shape : {sum_row_mat2.shape} ndim : {sum_row_mat2.ndim} \n{sum_row_mat2}")

sum_col_mat1 = mat_d.sum(axis=1, keepdims=True)
print("\n============Matrix | Keepdims=True ============")
print(f"sum_col_mat shape : {sum_col_mat1.shape} ndim : {sum_col_mat1.ndim} \n{sum_col_mat1}")

sum_col_mat2 = mat_d.sum(axis=1, keepdims=False)
print("\n============Matrix | Keepdims=False ============")
print(f"sum_col_mat shape : {sum_col_mat2.shape} ndim : {sum_col_mat2.ndim} \n{sum_col_mat2}")

mat_d shape : (3, 4) ndim : 2 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

============Matrix | Keepdims=True ============
sum_row_mat shape : (1, 4) ndim : 2 
[[12 15 18 21]]

============Matrix | Keepdims=False ============
sum_row_mat shape : (4,) ndim : 1 
[12 15 18 21]

============Matrix | Keepdims=True ============
sum_col_mat shape : (3, 1) ndim : 2 
[[ 6]
 [22]
 [38]]

============Matrix | Keepdims=False ============
sum_col_mat shape : (3,) ndim : 1 
[ 6 22 38]


In [41]:
import numpy as np 

ten_a = np.arange(24).reshape(2 , 3, 4)

for dim in range(len(ten_a)):
    for row in range(len(ten_a[dim])):
        print()
        for col in range(len(ten_a[dim][row])):
            print(f"ten_a[{dim}][{row}][{col}] : {ten_a[dim][row][col]}", end= " ")
        print(end= " ")

sum_col = ten_a.sum(axis=2)
print("\n============Axis=2, Keepdims=False ============")
print(f"sum_col shapea{sum_col.shape} ndim {sum_col.ndim}\n {sum_col}")
sum_col2 = ten_a.sum(axis=2 , keepdims=True)
print("\n============Axis=2, Keepdims=True ============")
print(f"sum_col2 shapea{sum_col2.shape} ndim {sum_col2.ndim}\n {sum_col2}")



ten_a[0][0][0] : 0 ten_a[0][0][1] : 1 ten_a[0][0][2] : 2 ten_a[0][0][3] : 3  
ten_a[0][1][0] : 4 ten_a[0][1][1] : 5 ten_a[0][1][2] : 6 ten_a[0][1][3] : 7  
ten_a[0][2][0] : 8 ten_a[0][2][1] : 9 ten_a[0][2][2] : 10 ten_a[0][2][3] : 11  
ten_a[1][0][0] : 12 ten_a[1][0][1] : 13 ten_a[1][0][2] : 14 ten_a[1][0][3] : 15  
ten_a[1][1][0] : 16 ten_a[1][1][1] : 17 ten_a[1][1][2] : 18 ten_a[1][1][3] : 19  
ten_a[1][2][0] : 20 ten_a[1][2][1] : 21 ten_a[1][2][2] : 22 ten_a[1][2][3] : 23  
============Axis=2, Keepdims=False ============
sum_col shapea(2, 3) ndim 2
 [[ 6 22 38]
 [54 70 86]]

============Axis=2, Keepdims=True ============
sum_col2 shapea(2, 3, 1) ndim 3
 [[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]


In [46]:
import numpy as np 

np.random.seed(30)
num_test_time, num_student, num_subject = 4, 3, 4 
min_sccore, max_score =50, 100 
ten_score = np.random.randint(low = min_sccore, 
                              high = max_score,
                              size= (num_test_time,
                                     num_student, 
                                     num_subject))

print(f"ten_score shape : {ten_score.shape}, ndim : {ten_score.ndim} \n {ten_score}")
# subject student sum 
sum_score = ten_score.sum(axis=0)
# subject sum
sum_score = ten_score.sum(axis=1)
mean_score = ten_score.mean(axis=0)
print(f"mean_total :  shape {mean_score.shape} , ndim {mean_score.ndim} \n{mean_score}")
print(f"sum_total :  shape {sum_score.shape} , ndim {sum_score.ndim} \n{sum_score}")


ten_score shape : (4, 3, 4), ndim : 3 
 [[[87 87 95 95]
  [62 73 52 67]
  [96 53 91 57]]

 [[51 99 95 85]
  [68 68 88 62]
  [66 56 77 96]]

 [[95 50 61 65]
  [73 86 63 83]
  [78 99 77 64]]

 [[90 61 81 95]
  [94 87 61 89]
  [59 83 97 89]]]
mean_total :  shape (3, 4) , ndim 2 
[[80.75 74.25 83.   85.  ]
 [74.25 78.5  66.   75.25]
 [74.75 72.75 85.5  76.5 ]]
sum_total :  shape (4, 4) , ndim 2 
[[245 213 238 219]
 [185 223 260 243]
 [246 235 201 212]
 [243 231 239 273]]


In [48]:
import numpy as np 

C, H, W = 3, 100, 200 
# channel axis = 0  
# 
images =  np.random.randint(0, 256, size=(C, H, W))
print(f"shape of original image : {images.shape}")

shape of original image : (3, 100, 200)
