In [5]:
# Overall Repetition 
# Repeating ndarrays 
# np.tile(A, reps)
import numpy as np 

vec_a = np.arange(4).reshape(-1, 1)
print(f"ndarray : shape{vec_a.shape} \n{vec_a}")

print("======repeat======")
rep_vec = np.repeat(vec_a, repeats=3, axis=1)
print(f"repeat ndarray  shape {rep_vec.shape} \n {rep_vec}")


print("======tile======")
vec_b = np.arange(4)
tile_vec = np.tile(vec_b, reps=3)
print(f"tile ndarray shape {tile_vec.shape} \n {tile_vec}")

ndarray : shape(4, 1) 
[[0]
 [1]
 [2]
 [3]]
======repeat======
repeat ndarray  shape (4, 3) 
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
======tile======
tile ndarray shape (12,) 
 [0 1 2 3 0 1 2 3 0 1 2 3]


In [10]:
import numpy as np 

vec_a = np.arange(3)
print(f"ndarray : {vec_a.shape} \n{vec_a}")

tile_vec = np.tile(vec_a, reps=(1, 2))
print(f"tile ndarray {tile_vec.shape} \n{tile_vec}")

tile_vec = np.tile(vec_a, reps=[2,1])
print(f"tile ndarray {tile_vec.shape} \n{tile_vec}")


tile_vec = np.tile(vec_a, reps=[2,2])
print(f"tile ndarray {tile_vec.shape} \n{tile_vec}")


ndarray : (3,) 
[0 1 2]
tile ndarray (1, 6) 
[[0 1 2 0 1 2]]
tile ndarray (2, 3) 
[[0 1 2]
 [0 1 2]]
tile ndarray (2, 6) 
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [16]:
import numpy as np 

mat_a = np.arange(6).reshape(2, 3)
print(f"ndarray : shape{mat_a.shape} \n{mat_a}")

# row repeat once
# column repeat twice 
tile_mat = np.tile(mat_a, reps=[1, 2])
print(f"tile ndarray reps [1, 2]: shape{tile_mat.shape} \n{tile_mat}")

tile_mat = np.tile(mat_a, reps=[2, 1])
print(f"tile ndarray reps [2, 1]: shape{tile_mat.shape} \n{tile_mat}")

tile_mat = np.tile(mat_a, reps=[2, 2])
print(f"tile ndarray reps [2, 2]: shape{tile_mat.shape} \n{tile_mat}")

ndarray : shape(2, 3) 
[[0 1 2]
 [3 4 5]]
tile ndarray reps [1, 2]: shape(2, 6) 
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
tile ndarray reps [2, 1]: shape(4, 3) 
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
tile ndarray reps [2, 2]: shape(4, 6) 
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [30]:
import numpy as np 

mat_a = np.arange(6).reshape(2, 3)
print(f"ndarray : {mat_a.shape} \n{mat_a}")

reps_a = np.array([3, 5])
tile_mat = np.tile(mat_a, reps=reps_a)
print(f"ndarray reps[{reps_a}] shape {tile_mat.shape} \n{tile_mat}")

reps_a = np.array([10, 8])
tile_mat = np.tile(mat_a, reps=reps_a)
print(f"ndarray reps[{reps_a}] shape {tile_mat.shape} \n{tile_mat}")


ndarray : (2, 3) 
[[0 1 2]
 [3 4 5]]
ndarray reps[[3 5]] shape (6, 15) 
[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]]
ndarray reps[[10  8]] shape (20, 24) 
[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 

In [41]:
import numpy as np 

mat_a = np.arange(6).reshape((2, 3))
print(f"mat_a : shape {mat_a.shape}")

reps_a = np.array([3, 5])
tile = np.tile(mat_a, reps=reps_a)
print(f"shape : {tile.shape} - {reps_a *mat_a.shape}") 
print(f"{tile}")

mat_b = np.arange(6).reshape(2, 3)
reps_b = np.array([10, 8])
tile = np.tile(mat_b, reps=reps_b)
print(f"tile shape {tile.shape} \n{tile}")


# row vector 
mat_c = np.arange(4).reshape(1, -1)
tile = np.tile(mat_c, reps=[5, 1])
print(f"tile shpae {tile.shape} \n{tile}")

# column vector

mat_d = np.arange(4).reshape(-1, 1) 
tile = np.tile(mat_d, reps=[1, 5])
print(f"tile shape {tile.shape} \n{tile}")

mat_a : shape (2, 3)
shape : (6, 15) - [ 6 15]
[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]]
tile shape (20, 24) 
[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2

In [29]:
import numpy  as np 

mat_a = np.arange(4).reshape((1, -1))
print(f"ndarray : {mat_a.shape }\n {mat_a}")
tile_mat = np.tile(mat_a, reps=[5, 1])
print(f"ndarray reps[1, 5] shape {tile_mat.shape} \n{tile_mat}")

mat_b = np.arange(4).reshape(-1, 1)
print(f"ndarray shape {mat_b.shape}\n{mat_b}")
tile_mat = np.tile(mat_b, reps=[1, 5])
print(f"ndarray reps[5, 1] shape {tile_mat.shape} \n{tile_mat}")

ndarray : (1, 4)
 [[0 1 2 3]]
ndarray reps[1, 5] shape (5, 4) 
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
ndarray shape (4, 1)
[[0]
 [1]
 [2]
 [3]]
ndarray reps[5, 1] shape (4, 5) 
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
