In [9]:
# Merging ndarrays 
# hstack vstack 
import numpy as np 

# vector 
vec_a = np.arange(8)
vec_b = np.arange(9, 17)
print(f"vec_a :{vec_a}")
print(f"vec_b :{vec_b}")

# vertical 
vstack = np.vstack([vec_a, vec_b])
print(f"vstack : shape {vstack.shape}\n{vstack}")

# horizontal 
hstack = np.hstack([vec_a, vec_b])
print(f"hstack : shape {hstack.shape} \n{hstack}")


vec_a :[0 1 2 3 4 5 6 7]
vec_b :[ 9 10 11 12 13 14 15 16]
vstack : shape (2, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15 16]]
hstack : shape (16,) 
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 16]


In [13]:
import numpy as np 
np.random.seed(30)
# row vector 
mat_a = np.random.randint(0, 10, (1, 3))
mat_b = np.random.randint(0, 10, (1, 3))

print(f"mat_a shape{mat_a.shape} :\n{mat_a}")
print(f"mat_b shape{mat_b.shape} :\n{mat_b}")

vstack = np.vstack((mat_a, mat_b))
print(f"vstack : shape {vstack.shape} \n{vstack}")


hstack = np.hstack((mat_a, mat_b))
print(f"hstack : shape {hstack.shape} \n{hstack}")

mat_a shape(1, 3) :
[[5 5 4]]
mat_b shape(1, 3) :
[[7 2 5]]
vstack : shape (2, 3) 
[[5 5 4]
 [7 2 5]]
hstack : shape (1, 6) 
[[5 5 4 7 2 5]]


In [15]:
import numpy as np 
np.random.seed(30)
# column vector 
mat_a =np.random.randint(0, 10, (3, 1))
mat_b =np.random.randint(0, 10, (3, 1))

print(f"mat_a shape{mat_a.shape} :\n{mat_a}")
print(f"mat_b shape{mat_b.shape} :\n{mat_b}")

vstack = np.vstack((mat_a, mat_b))
hstack = np.hstack((mat_a, mat_b))
print(f"vstack : shape {vstack.shape} \n{vstack}")
print(f"hstack : shape {hstack.shape} \n{hstack}")


mat_a shape(3, 1) :
[[5]
 [5]
 [4]]
mat_b shape(3, 1) :
[[7]
 [2]
 [5]]
vstack : shape (6, 1) 
[[5]
 [5]
 [4]
 [7]
 [2]
 [5]]
hstack : shape (3, 2) 
[[5 7]
 [5 2]
 [4 5]]


In [53]:
import numpy as np 
np.random.seed(30)
#matrix vector 
#vertical 
mat_a = np.random.randint(0, 10, (3, 4))
vec_a = np.random.randint(0, 10, (4, ))

print(f"mat_a shape{mat_a.shape} :\n{mat_a}")
print(f"vec_a shape{vec_a.shape} :\n{vec_a}")

vstack = np.vstack([vec_a, mat_a])
print(f"vstack : shape {vstack.shape} \n{vstack}")



mat_a shape(3, 4) :
[[5 5 4 7]
 [2 5 1 3]
 [9 7 7 1]]
vec_a shape(4,) :
[1 3 2 2]
vstack : shape (4, 4) 
[[1 3 2 2]
 [5 5 4 7]
 [2 5 1 3]
 [9 7 7 1]]


In [54]:
import numpy as np 
np.random.seed(30)
#matrix vector 
# horizontal 

mat_a = np.random.randint(0, 10, (3, 4))
vec_a = np.random.randint(0, 10, (3, ))

print(f"mat_a shape{mat_a.shape} :\n{mat_a}")
print(f"vec_a shape{vec_a.shape} :\n{vec_a}")

# hstack = np.hstack([vec_a, mat_a])
# print(f"hstack : shape {hstack.shape} \n{hstack}")
hstack = np.hstack([mat_a, vec_a.reshape(-1, 1)]) 
print(f"hstack : shape {hstack.shape} \n{hstack}")

mat_a shape(3, 4) :
[[5 5 4 7]
 [2 5 1 3]
 [9 7 7 1]]
vec_a shape(3,) :
[1 3 2]
hstack : shape (3, 5) 
[[5 5 4 7 1]
 [2 5 1 3 3]
 [9 7 7 1 2]]


In [75]:
import numpy as np 

dataset = np.empty((0, 4))
print(f"ds shape {dataset.shape}")

for iter in range(5):
    data_sample = np.random.uniform(0, 5, (1, 4))
    dataset = np.vstack((dataset, data_sample))
    #print(dataset)
    print(f"iter/shape : {iter}/{dataset.shape}")

ds shape (0, 4)
iter/shape : 0/(1, 4)
iter/shape : 1/(2, 4)
iter/shape : 2/(3, 4)
iter/shape : 3/(4, 4)
iter/shape : 4/(5, 4)


In [79]:
import numpy as np 
dataset = np.empty((4, 0))
print(f"ds shape {dataset.shape}" )

for inter in range(5):
    data_sample = np.random.uniform(0, 5, (4, 1))
    dataset= np.hstack((dataset, data_sample))
    print(f"iter/shape : {iter}/{dataset.shape}")

ds shape (4, 0)
iter/shape : 4/(4, 1)
iter/shape : 4/(4, 2)
iter/shape : 4/(4, 3)
iter/shape : 4/(4, 4)
iter/shape : 4/(4, 5)


In [90]:
import numpy as np 

# dataset = np.empty((4, 0))
# print(f"initial dataset shape: {dataset.shape}\n")

# for iter in range(5):
#     data_sample = np.random.uniform(0, 5, (4, 1))
#     dataset = np.hstack((dataset, data_sample))
#     print(f"iter/shape {iter}/{dataset.shape}")

a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4))
c = np.random.randint(0, 10, (1, 4))

arr_list = [a, b, c]

# for idx in range(len(arr_list)):
#     for row in range(len(arr_list[idx])):
#         for col in range(len(arr_list[idx][row])):
#             print(f"arr_list[{idx}][{row}][{col}] : {arr_list[idx][row][col]}")

vstack = np.vstack(arr_list)

print(f"a : {a.shape}\n {a}")
print(f"b : {b.shape}\n {b}")
print(f"c : {c.shape}\n {c}")

print(f"vstack : {vstack.shape} \n{vstack}")





a : (1, 4)
 [[1 6 2 1]]
b : (1, 4)
 [[4 0 1 8]]
c : (1, 4)
 [[7 1 1 0]]
vstack : (3, 4) 
[[1 6 2 1]
 [4 0 1 8]
 [7 1 1 0]]


In [92]:
import numpy as np 

dataset_tmp = list()
for iter in range(100):
    data_sample = np.random.uniform(0, 5, (1, 4))
    dataset_tmp.append(data_sample)

dataset = np.vstack(dataset_tmp)
print(f"dataset : {dataset.shape}\n{dataset}")

dataset : (100, 4)
[[4.976475   4.96646742 1.98346242 0.34901992]
 [1.89131284 4.07526576 4.02519299 0.51391352]
 [4.34864481 2.75318312 0.83110483 1.83018263]
 [3.0326656  1.30081592 0.95728207 3.48761494]
 [2.72337492 4.51484451 4.23101367 4.83423139]
 [0.7553647  2.87608121 4.71193917 0.74981928]
 [0.3267714  0.81381571 1.29354519 4.4183876 ]
 [4.76238912 2.87047537 4.33775648 1.97422291]
 [3.08348108 3.91439978 0.79064309 3.48328013]
 [2.12536845 4.07837888 1.78988529 1.29459864]
 [2.74061437 0.94442232 1.99077416 3.12302916]
 [2.57757384 4.19828694 2.06993115 3.4293194 ]
 [4.53253259 2.47148349 3.92795389 1.48602714]
 [4.56007247 3.66979466 0.9692182  0.73318681]
 [1.94595054 3.81632347 3.73105148 3.49924118]
 [3.86665975 1.90592825 0.15616442 3.19878782]
 [2.01945016 0.71855344 1.4021629  1.4466654 ]
 [1.99932601 1.37505759 1.76705158 4.61437857]
 [0.63553638 3.80757619 3.15584231 3.73855628]
 [0.6877057  0.28852632 0.880814   1.70134874]
 [0.30104421 4.65894487 1.75282873 3.7173