### Numpy
##### 1 Numpy 
- Scalar : Zeroth-Order Tensors 
- Vector : First Order Tensors
- Matric : Second Order Tensors 
- Tensors 


In [12]:
import numpy as np 
score = [10, 20, 30, 40, 50]
# print("mean", np.mean(score))
# print("mean", np.var(score))
# a= np.array([1, 2, 3])

# print(type(a))
# for attr in dir(a):
#     print(attr)

u = [1, 2, 3]
v = [4, 5, 6]
w = [0] * len(u)

# python add 
for data_idx in range(len(u)):
    w[data_idx] = u[data_idx] + v[data_idx]
print(w)

# numpy add 
np_n = np.array(u)
np_v = np.array(v)
print(np_n + np_v)

M = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]]
N = [[11, 12, 13], 
     [14, 15, 16],
     [17, 18, 19]]
print(M + N)

N_row, N_col = len(M), len(M[0])

P = [[0] * N_col for _ in range(N_col)]


for row in range(N_row):
    for col in range(N_col):
        P[row][col] = M[row][col]+ N[row][col]

print(P)    

[5, 7, 9]
[5 7 9]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13], [14, 15, 16], [17, 18, 19]]
[[12, 14, 16], [18, 20, 22], [24, 26, 28]]


In [24]:
import numpy as np 
int_py = 3 
float_py = 3.14 

int_np = np.array(int_py)
float_np = np.array(float_py)

# print(type(int_np))
# print(type(float_np))
# print(int_np, int_py, sep="-")
# print(float_np, float_py, sep="-")

# vec_py = [1, 2, 3]
# vec_np = np.array(vec_py)
# print(vec_np, vec_py, sep="-")

# mat_py =[[1, 2, 3], [4, 5, 6]]
# mat_np = np.array(mat_py)
# print(mat_np, mat_py, sep="\n\n")

# tensor_py = [[[1, 2, 3],
#               [4, 5, 6]],
#              [[11, 12, 13],
#               [14, 15, 16]]]
# tensor_np = np.array(tensor_py)
# print(tensor_np, tensor_py, sep="\n\n")

scalar_np = np.array(3.14)
vec_np = np.array([1, 2, 3])
mat_np = np.array([[1, 2], [3, 4]])
tensor_np = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                      [[11, 12, 13],
                       [14, 15, 16]]])

print(scalar_np.shape)
print(vec_np.shape)
print(mat_np.shape)
print(tensor_np.shape)

print(len(()))
print(len((3, )))
print(len((2, 2)))
print(len((2, 2, 3)))

()
(3,)
(2, 2)
(2, 2, 3)
0
1
2
3


In [44]:
# ndarry with Specific Values 

# zero_np = np.zeros(shape=(2, 3))
# print(zero_np.shape)
# print(zero_np)

# one_np = np.ones(shape=(7, 4))
# print(one_np.shape)
# print(one_np)

# full_np = np.full(shape=(2, 3), fill_value=3.14)
# print(full_np.shape)
# print(full_np)
# print("\n")

# empty_np = np.empty(shape=(2, 3))
# print(empty_np.shape)
# print(empty_np)

# print("\n\n")
M = np.full(shape=(2, 3), fill_value=3.14)
print(M.shape)
print(M)

zero_like = np.zeros_like(M)
one_like = np.ones_like(M)
full_like = np.full_like(M, fill_value=100)
empty_like = np.empty_like(M)

print(zero_like)
print(one_like)
print(full_like)
print(empty_like)


(2, 3)
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100. 100. 100.]
 [100. 100. 100.]]
[[100. 100. 100.]
 [100. 100. 100.]]


In [58]:
# Making ndarrays with Fixed intervals 

# python 
print(list(range(10)))
print(list(range(2, 5)))
print(list(range(2, 10, 2)))

print("\n")
#numpy 
print(np.arange(10))
print(np.arange(2, 5))
print(np.arange(2, 10, 2))

print(np.arange(10.5))
print(np.arange(1.5, 10.5))
print(np.arange(1.5, 10.5, 2.5))

# Making ndarrays with Fixed Points 
# fist value, last value! 
print(np.linspace(0, 1, 5))
a = np.linspace([1, 10, 100], [2, 20, 200], 5)
print(a)
print("\n")

print(np.arange(0, 1 + 0.25, 0.25))
print(np.linspace(0, 1, 5))

print(np.arange(10))
print(np.linspace(0, 9, 10))

print(np.arange(5, 10))
print(np.linspace(5, 9, 9-5+1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4]
[2, 4, 6, 8]


[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4 6 8]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
[1.5 4.  6.5 9. ]
[0.   0.25 0.5  0.75 1.  ]
[[  1.    10.   100.  ]
 [  1.25  12.5  125.  ]
 [  1.5   15.   150.  ]
 [  1.75  17.5  175.  ]
 [  2.    20.   200.  ]]


[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[5 6 7 8 9]
[5. 6. 7. 8. 9.]
