In [8]:
import numpy as np 
# Indexing and Slicing ndarrays 
# Tensor Indexing Slicing 

ten_a = np.arange(27).reshape(3, 3, 3)
print(ten_a.ndim, ten_a.shape)

for dim in range(len(ten_a)):
    print()
    for row in range(len(ten_a[dim])):
        for col in range(len(ten_a[row])):
            print(f"ten_a[{dim}][{row}][{col}] : {ten_a[dim][row][col]}", end=" ")
        print() 
print()

# print(ten_a[0])
# print(ten_a[1])
# print(ten_a[2])

print("ten_a[0, 0] \n {}".format(ten_a[0, 0]))
print("ten_a[0, :2, :2] \n {}".format(ten_a[0, :2, :2]))
print("ten_a[1, :2, :] \n {}".format(ten_a[1, :2, :]))
print("ten_a[2, -2:, -2:] \n {}".format(ten_a[2, -2:, -2:]))

3 (3, 3, 3)

ten_a[0][0][0] : 0 ten_a[0][0][1] : 1 ten_a[0][0][2] : 2 
ten_a[0][1][0] : 3 ten_a[0][1][1] : 4 ten_a[0][1][2] : 5 
ten_a[0][2][0] : 6 ten_a[0][2][1] : 7 ten_a[0][2][2] : 8 

ten_a[1][0][0] : 9 ten_a[1][0][1] : 10 ten_a[1][0][2] : 11 
ten_a[1][1][0] : 12 ten_a[1][1][1] : 13 ten_a[1][1][2] : 14 
ten_a[1][2][0] : 15 ten_a[1][2][1] : 16 ten_a[1][2][2] : 17 

ten_a[2][0][0] : 18 ten_a[2][0][1] : 19 ten_a[2][0][2] : 20 
ten_a[2][1][0] : 21 ten_a[2][1][1] : 22 ten_a[2][1][2] : 23 
ten_a[2][2][0] : 24 ten_a[2][2][1] : 25 ten_a[2][2][2] : 26 

ten_a[0, 0] 
 [0 1 2]
ten_a[0, :2, :2] 
 [[0 1]
 [3 4]]
ten_a[1, :2, :] 
 [[ 9 10 11]
 [12 13 14]]
ten_a[2, -2:, -2:] 
 [[22 23]
 [25 26]]


In [13]:
ten_b = np.arange(3*3*3).reshape(3, 3, 3)
print(ten_b.ndim, ten_b.shape)

for dim in range(len(ten_b)):
    print()
    for row in range(len(ten_b[dim])):
        for col in range(len(ten_b[row])):
            print(f"ten_b[{dim}][{row}][{col}] : {ten_b[dim][row][col]}", end=" ")
        print() 
print()


print("ten_b[0, :2, :2] \n {}".format(ten_b[0, :2, :2]))
print("ten_b[1, :2, :2] \n {}".format(ten_b[1, :2, :]))
print("ten_b[2, -2:, -2:] \n {}".format(ten_b[2, -2:, -2:]))


3 (3, 3, 3)

ten_b[0][0][0] : 0 ten_b[0][0][1] : 1 ten_b[0][0][2] : 2 
ten_b[0][1][0] : 3 ten_b[0][1][1] : 4 ten_b[0][1][2] : 5 
ten_b[0][2][0] : 6 ten_b[0][2][1] : 7 ten_b[0][2][2] : 8 

ten_b[1][0][0] : 9 ten_b[1][0][1] : 10 ten_b[1][0][2] : 11 
ten_b[1][1][0] : 12 ten_b[1][1][1] : 13 ten_b[1][1][2] : 14 
ten_b[1][2][0] : 15 ten_b[1][2][1] : 16 ten_b[1][2][2] : 17 

ten_b[2][0][0] : 18 ten_b[2][0][1] : 19 ten_b[2][0][2] : 20 
ten_b[2][1][0] : 21 ten_b[2][1][1] : 22 ten_b[2][1][2] : 23 
ten_b[2][2][0] : 24 ten_b[2][2][1] : 25 ten_b[2][2][2] : 26 

ten_b[0, :2, :2] 
 [[0 1]
 [3 4]]
ten_b[1, :2, :2] 
 [[ 9 10 11]
 [12 13 14]]
ten_b[2, -2:, -2:] 
 [[22 23]
 [25 26]]


In [19]:
ten_c = np.arange(3*3*3).reshape(3, 3, 3)
print(ten_c.ndim, ten_c.shape)

for dim in range(len(ten_c)):
    print()
    for row in range(len(ten_c[dim])):
        for col in range(len(ten_c[row])):
            print(f"ten_c[{dim}][{row}][{col}] : {ten_c[dim][row][col]}", end=" ")
        print() 
print()

print("ten_c[:, :2, :] \n {}".format(ten_c[:, :2, :]))
print("ten_c[:, :, :1] \n {}".format(ten_c[:, :, :1]))
print("ten_c[1:, 1:, 1:] \n {}".format(ten_c[1:, 1:, 1:]))

3 (3, 3, 3)

ten_c[0][0][0] : 0 ten_c[0][0][1] : 1 ten_c[0][0][2] : 2 
ten_c[0][1][0] : 3 ten_c[0][1][1] : 4 ten_c[0][1][2] : 5 
ten_c[0][2][0] : 6 ten_c[0][2][1] : 7 ten_c[0][2][2] : 8 

ten_c[1][0][0] : 9 ten_c[1][0][1] : 10 ten_c[1][0][2] : 11 
ten_c[1][1][0] : 12 ten_c[1][1][1] : 13 ten_c[1][1][2] : 14 
ten_c[1][2][0] : 15 ten_c[1][2][1] : 16 ten_c[1][2][2] : 17 

ten_c[2][0][0] : 18 ten_c[2][0][1] : 19 ten_c[2][0][2] : 20 
ten_c[2][1][0] : 21 ten_c[2][1][1] : 22 ten_c[2][1][2] : 23 
ten_c[2][2][0] : 24 ten_c[2][2][1] : 25 ten_c[2][2][2] : 26 

ten_c[:, :2, :] 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
ten_c[:, :, :1] 
 [[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]

 [[18]
  [21]
  [24]]]
ten_c[1:, 1:, 1:] 
 [[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [27]:
import numpy as np 

image = np.random.normal(size=(3, 500, 300))

# image_r = image[0]
# image_g = image[1]
# image_b = image[2]

image_r, image_g, image_b = image
print(image_r.shape, image_g.shape, image_b.shape)

top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]

print(top_left.shape, top_right.shape)
print(bottom_left.shape, bottom_right.shape)

(500, 300) (500, 300) (500, 300)
(3, 100, 100) (3, 100, 100)
(3, 100, 100) (3, 100, 100)
