In [18]:
import numpy as np 
# Element-wise Operations and Broadcasting 

np.random.seed(30)
a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))

print("a : ", a)
print("b : ", b)
print("a + b   : ", (a + b))
print("a - b   : ", (a - b))
print("a * b   : ", (a *  b))
print("a / b   : ", (a /  b))
print("a // b  : ", (a // b))
print("a % b   : ", (a %  b))
print("a ** b  : ", (a ** b))
print("\n\n")
print("a + b   : ", a.__add__(b))
print("a - b   : ", a.__sub__(b))
print("a * b   : ", a.__mul__(b))
print("a / b   : ", a.__truediv__(b))
print("a // b  : ", a.__floordiv__(b))
print("a % b   : ", a.__mod__(b))
print("a ** b  : ", a.__pow__(b))

print("a > b : " , a > b)
print("a > b : " , a >= b)
print("a > b : " , a < b)
print("a > b : " , a <= b)
print("a == b : " , a == b)
print("a != b : " , a != b)

mat_np1 = np.random.randint(1, 5, (2, 3))
mat_np2 = np.random.randint(1, 5, (2, 3))

print("mat_np1 :\n" , mat_np1)
print("mat_np2 :\n" , mat_np2)

print("mat_np1 + mat_np2 :\n", mat_np1 + mat_np2)
print("mat_np1 - mat_np2 :\n", mat_np1 - mat_np2) 

print("mat_np1 > mat_np2 :\n", mat_np1 > mat_np2)
print("mat_np1 >= mat_np2 :\n", mat_np1 >= mat_np2)

a = np.array(5)
mask = np.array([0, 1, 0, 1, 0])

print("input :", a)
print("mask :", mask)
print("output :", a*mask)


a :  [2 2 2 2 1]
b :  [1 4 3 2 4]
a + b   :  [3 6 5 4 5]
a - b   :  [ 1 -2 -1  0 -3]
a * b   :  [2 8 6 4 4]
a / b   :  [2.         0.5        0.66666667 1.         0.25      ]
a // b  :  [2 0 0 1 0]
a % b   :  [0 2 2 0 1]
a ** b  :  [ 2 16  8  4  1]



a + b   :  [3 6 5 4 5]
a - b   :  [ 1 -2 -1  0 -3]
a * b   :  [2 8 6 4 4]
a / b   :  [2.         0.5        0.66666667 1.         0.25      ]
a // b  :  [2 0 0 1 0]
a % b   :  [0 2 2 0 1]
a ** b  :  [ 2 16  8  4  1]
a > b :  [ True False False False False]
a > b :  [ True False False  True False]
a > b :  [False  True  True False  True]
a > b :  [False  True  True  True  True]
a == b :  [False False False  True False]
a != b :  [ True  True  True False  True]
mat_np1 :
 [[2 3 4]
 [2 4 4]]
mat_np2 :
 [[2 2 2]
 [2 4 3]]
mat_np1 + mat_np2 :
 [[4 5 6]
 [4 8 7]]
mat_np1 - mat_np2 :
 [[0 1 2]
 [0 0 1]]
mat_np1 > mat_np2 :
 [[False  True  True]
 [False False  True]]
mat_np1 >= mat_np2 :
 [[ True  True  True]
 [ True  True  True]]
input : 5
mask

In [49]:
# Broadcasting Cases 

# When ndims Are Equal(Matrices)

mat_np = np.arange(9).reshape(3, 3)
# vec_np = np.array([[0, 10, 20]])
# vec_np = 10 * np.arange(3).reshape(-1, 3)
vec_np = 10* np.arange(3).reshape(-1, 3)

print(mat_np)
print(vec_np)

print("mat_np{} / {}".format(mat_np.shape, mat_np.ndim))
print("vec_np{} / {}".format(vec_np.shape, vec_np.ndim))
print(mat_np + vec_np)

print("\n\n")
vec_np = 10 * np.arange(3).reshape(3, -1)
print(vec_np)


print("mat_np{} / {}".format(mat_np.shape, mat_np.ndim))
print("vec_np{} / {}".format(vec_np.shape, vec_np.ndim))
print(mat_np + vec_np)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0 10 20]]
mat_np(3, 3) / 2
vec_np(1, 3) / 2
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]]



[[ 0]
 [10]
 [20]]
mat_np(3, 3) / 2
vec_np(3, 1) / 2
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


In [51]:
col_mat = np.arange(3).reshape(3, -1)
row_mat = np.arange(3).reshape(-1, 3)

print("col_mat {} / {}".format(col_mat.shape, col_mat.ndim))
print("row_mat {} / {}".format(row_mat.shape, row_mat.ndim))
print(col_mat)
print(row_mat)


col_mat (3, 1) / 2
row_mat (1, 3) / 2
[[0]
 [1]
 [2]]
[[0 1 2]]


In [61]:
# Tensor Broadcasting 
ten_np1 = np.arange(18).reshape(2, 3, 3)
# print(ten_np1)
ten_np2 = 10*np.arange(9).reshape(1, 3, 3)
# print(ten_np2)
# print(ten_np1 + ten_np2)
# print("\n\n")

ten_np3 = 10*np.arange(6).reshape(2, 1, 3)
print(ten_np3)
print(ten_np1 + ten_np3)

ten_np4 = 10*np.arange(6).reshape(2, 3, 1)
print(ten_np4)
print(ten_np1 + ten_np4)

[[[ 0 10 20]]

 [[30 40 50]]]
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]
[[[ 0  1  2]
  [13 14 15]
  [26 27 28]]

 [[39 40 41]
  [52 53 54]
  [65 66 67]]]


In [73]:
# When ndims Are Not Equal 
# scalar vector 
a = np.array(3)
u = np.arange(1, 5)

print("a {}/{}".format(a.shape, a.ndim))
print("u {}/{}".format(u.shape, u.ndim))
print(a)
print(u)
print("a + u", a + u)
print("a - u", a - u)
print("a * u", a * u)
print("a // u", a // u)
print("a / u", a / u)
print("a % u", a & u)
print("a ** u", a ** u)

a = 10*np.array([1, 2])
b = np.arange(6).reshape(3, 2)
print(a)
print(b)
print(a + b)

a ()/0
u (4,)/1
3
[1 2 3 4]
a + u [4 5 6 7]
a - u [ 2  1  0 -1]
a * u [ 3  6  9 12]
a // u [3 1 1 0]
a / u [3.   1.5  1.   0.75]
a % u [1 2 3 0]
a ** u [ 3  9 27 81]
[10 20]
[[0 1]
 [2 3]
 [4 5]]
[[10 21]
 [12 23]
 [14 25]]


In [79]:
ten_np = np.arange(24).reshape(2, 3, 4)
print(ten_np.shape)

mat_np = 10*np.arange(12).reshape(3, 4)
print(mat_np.shape)

vec_np = 10*np.arange(4)
print(vec_np.shape)
"""_summary_
    Tensor:(2, 3, 4)
       Matrix:(3, 4)
       Vector:   (4)
    
   A:(a, b, c, d, e)
      B:(b, c, d, e)
         C:(c, d ,e)
            D:(d, e)
               E:(e)
"""

(2, 3, 4)
(3, 4)
(4,)
