In [5]:
# Dimensionality 
# Manipulations 

import numpy as np 

vec_a = np.arange(9)
print(f'vec_a shape{vec_a.shape} \n{vec_a}')

mat_a = vec_a.reshape(1, 9)
mat_b = vec_a.reshape(9, 1)
print(f'mat_a shape{mat_a.shape}\n{mat_a}')
print(f'mat_b shape{mat_b.shape}\n{mat_b}')

ten_a = vec_a.reshape(1, 9, 1)
ten_b = vec_a.reshape(1, 1, 9)
ten_c = vec_a.reshape(9, 1, 1)

print(f'ten_a shape{ten_a.shape}\n{ten_a}')
print(f'ten_b shape{ten_b.shape}\n{ten_b}')
print(f'ten_c shape{ten_c.shape}\n{ten_c}')



vec_a shape(9,) 
[0 1 2 3 4 5 6 7 8]
mat_a shape(1, 9)
[[0 1 2 3 4 5 6 7 8]]
mat_b shape(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
ten_a shape(1, 9, 1)
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
ten_b shape(1, 1, 9)
[[[0 1 2 3 4 5 6 7 8]]]
ten_c shape(9, 1, 1)
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [8]:
import numpy as np 

mat_a = np.random.normal(size=(100, 200))
ten_a = mat_a.reshape(1, 100, 200)
ten_b = mat_a.reshape(100, 200, 1)

print(f"ten_a : {ten_a.shape}")
print(f"ten_b : {ten_b.shape}")

ten_a : (1, 100, 200)
ten_b : (100, 200, 1)


In [13]:
# tuple unpacking 
import numpy as np 
tup_a = (10, 20)
print(tup_a)

mat_a = np.random.normal(size=(100, 500))

print(f"mat_a shape {mat_a.shape}")
print(f" * mat_a shape {mat_a.shape}")
print(*mat_a.shape)
print(1, *mat_a.shape)

(10, 20)
mat_a shape (100, 500)
 * mat_a shape (100, 500)
100 500
1 100 500


In [18]:
# Making new Dimensions 
# Using Slicing 

vec_a = np.arange(9)
print(f"vec_a \n {vec_a}")

row_vec1= vec_a[np.newaxis, :]
row_vec2= vec_a[None, :]

print(f"row_vec1 shape {row_vec1.shape}:\n {row_vec1}")
print(f"row_vec2 shape {row_vec2.shape}:\n {row_vec2}")


col_vec1= vec_a[:, np.newaxis]
col_vec2= vec_a[:, None]

print(f"col_vec1 shape {col_vec1.shape}:\n {col_vec1}")
print(f"col_vec2 shape {col_vec2.shape}:\n {col_vec2}")

vec_a 
 [0 1 2 3 4 5 6 7 8]
row_vec1 shape (1, 9):
 [[0 1 2 3 4 5 6 7 8]]
row_vec2 shape (1, 9):
 [[0 1 2 3 4 5 6 7 8]]
col_vec1 shape (9, 1):
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
col_vec2 shape (9, 1):
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [22]:
import numpy as np 

vec_a = np.arange(9)
print(f"ten_a {vec_a}")

ten_a = vec_a[np.newaxis, np.newaxis, :]
print(f"ten_a shpae {ten_a.shape} \n {ten_a}")

ten_b = vec_a[np.newaxis, :, np.newaxis]
print(f"ten_b shape {ten_b.shape}  \n{ten_b}")

ten_c = vec_a[:, np.newaxis, np.newaxis]
print(f"ten_c {ten_c.shape} \n {ten_c}")

ten_a [0 1 2 3 4 5 6 7 8]
ten_a shpae (1, 1, 9) 
 [[[0 1 2 3 4 5 6 7 8]]]
ten_b shape (1, 9, 1)  
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
ten_c (9, 1, 1) 
 [[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [25]:
import numpy as np 

mat_a = np.random.normal(size=(100, 200))
print(f"mat_a shape {mat_a.shape}")
ten_b = mat_a[np.newaxis, ...]
print(f"ten_b shape {ten_b.shape}")


mat_a shape (100, 200)
ten_b shape (1, 100, 200)


In [38]:
# Using expend_dims API 
import numpy as np 
vec_a = np.arange(9)
# print(f"vec_a : {vec_a}")
mat_b =np.expand_dims(vec_a, axis=1)
mat_c =np.expand_dims(vec_a, axis=0)
# print(f"mat_b : {mat_b}")
# print(f"mat_c : {mat_c}")

ten_b = np.expand_dims(vec_a, axis=(0, 1))
ten_c = np.expand_dims(vec_a, axis=(0, 2))
ten_d = np.expand_dims(vec_a, axis=(1, 2))
print(f"ten_b shpae {ten_b.shape} \n{ten_b}")

print(f"ten_c shpae {ten_c.shape} \n{ten_c}")
print(f"ten_d shpae {ten_d.shape} \n{ten_d}")

ten_b shpae (1, 1, 9) 
[[[0 1 2 3 4 5 6 7 8]]]
ten_c shpae (1, 9, 1) 
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
ten_d shpae (9, 1, 1) 
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]
