In [20]:
import numpy as np 
# Indexing and Slicing ndarrays 
# Matrix Indexing Slicing 

list_a = [[0, 1, 2], 
          [3, 4, 5], 
          [6, 7, 8]]
# print("list_a[0] : {}".format(list_a[0]))
# print("list_a[1] : {}".format(list_a[1]))
# print("list_a[2] : {}".format(list_a[2]))

# Matrix indexing 
mat_a = np.array(list_a)
for row in range(len(mat_a)):
    for col in range(len(mat_a[row])):
        print("mat_a[{}][{}] : {}".format(row, col, mat_a[row][col]), end=" ")
    print()

print()

print(mat_a)
# print("mat_a[0]: {}".format(mat_a[0]))
# print("mat_a[1]: {}".format(mat_a[1]))
# print("mat_a[2]: {}".format(mat_a[2]))
# print("mat_a[1][2]: {}".format(mat_a[1][2]))
# print("mat_a[1, 2]: {}".format(mat_a[1, 2]))
# print("mat_a[-1, 1]: {}".format(mat_a[-1, 1]))

# Matrix slicing
# print("mat_a[:]: {}".format(mat_a[:]))
# print("mat_a[::-1]: {}".format(mat_a[::-1]))
# print("mat_a[1:3:1] {}".format(mat_a[1:3:1]))
# print("mat_a[2::-1] {}".format(mat_a[2::-1]))

mat_b = np.arange(12).reshape(3, 4)

for row in range(len(mat_b)):
    for col in range(len(mat_b[row])):
        print(f"mat_b[{row}][{col}] : {mat_b[row][col]}", end= " ")
    print()

print("mat_a[0, 1: ]: {}".format(mat_b[0, 1:]))
# print("mat_a[::-1]: {}".format(mat_b[::-1]))
# print("mat_a[1:3:1] {}".format(mat_b[1:3:1]))
# print("mat_a[2::-1] {}".format(mat_b[2::-1]))



 


mat_a[0][0] : 0 mat_a[0][1] : 1 mat_a[0][2] : 2 
mat_a[1][0] : 3 mat_a[1][1] : 4 mat_a[1][2] : 5 
mat_a[2][0] : 6 mat_a[2][1] : 7 mat_a[2][2] : 8 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
mat_b[0][0] : 0 mat_b[0][1] : 1 mat_b[0][2] : 2 mat_b[0][3] : 3 
mat_b[1][0] : 4 mat_b[1][1] : 5 mat_b[1][2] : 6 mat_b[1][3] : 7 
mat_b[2][0] : 8 mat_b[2][1] : 9 mat_b[2][2] : 10 mat_b[2][3] : 11 
mat_a[0, 1: ]: [1 2 3]
