In [6]:
# Changing Demensions 
# Using np.swapaxes API 

import numpy as np 

ten_a = np.random.normal(size = (3, 4, 5, 6))
# (H, W, C) ->(W, H, C)

# two demetions 
print(f"ten_a shape : {ten_a.shape}")
ten_swap_a = np.swapaxes(ten_a, 0, 1)
ten_swap_b = np.swapaxes(ten_a, 0, 2)
ten_swap_c = np.swapaxes(ten_a, 0, 3)
print(f"ten_swap_a shape : {ten_swap_a.shape}")
print(f"ten_swap_b shape : {ten_swap_b.shape}")
print(f"ten_swap_c shape : {ten_swap_c.shape}")




ten_a shape : (3, 4, 5, 6)
ten_swap_a shape : (4, 3, 5, 6)
ten_swap_a shape : (5, 4, 3, 6)
ten_swap_a shape : (6, 4, 5, 3)


In [8]:
import numpy as np 

ten_a = np.random.normal(size=(3, 200, 100))
ten_b = np.swapaxes(ten_a, 0, -1)
print(f"ten_a shape : {ten_a.shape}")
print(f"ten_b shape : {ten_b.shape}")

ten_a shape : (3, 200, 100)
ten_b shape : (100, 200, 3)


In [6]:
import numpy as np 
# Using np.moveaxis API 

ten_a = np.array([[[[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]]],
                  [[[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]]],
                  [[[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]],
                   [[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 39]]]])
print(ten_a.shape)

ten_b = np.moveaxis(ten_a, source=0, destination=1)
ten_c = np.moveaxis(ten_a, source=0, destination=2)
ten_d = np.moveaxis(ten_a, source=0, destination=-1)
print(f"ten_a shape : {ten_a.shape}")
print(ten_a[0, 0, ::])
print(ten_b[0, 0, ::])
print(f"ten_b shape : {ten_b.shape}")
print(f"ten_c shape : {ten_c.shape}")
print(f"ten_d shape : {ten_d.shape}")

ten_a = np.random.normal(size=(3, 4, 5, 6))
ten_b = np.moveaxis(ten_a, source = 0, destination=-1)
ten_b = np.moveaxis(ten_b, source = -2, destination=0)
print(f"ten_a shape : {ten_a.shape}")
print(f"ten_b shape : {ten_b.shape}")


(3, 4, 5, 6)
ten_a shape : (3, 4, 5, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 39]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 39]]
ten_b shape : (4, 3, 5, 6)
ten_c shape : (4, 5, 3, 6)
ten_d shape : (4, 5, 6, 3)
ten_a shape : (3, 4, 5, 6)
ten_b shape : (6, 4, 5, 3)


In [13]:
# Using np.transpose API 

import numpy as np 

mat_a = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(f"mat_a shape{mat_a.shape} \n{mat_a}")

mat_transpose = np.transpose(mat_a)
print(f"mat_transpose shape{mat_transpose.shape} \n{mat_transpose}")
mat_t = mat_a.T
print(f"mat_T shape{mat_t.shape} \n{mat_t}")


mat_a shape(3, 4) 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
mat_transpose shape(4, 3) 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
mat_T shape(4, 3) 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [26]:
import numpy as np 
# Using np.transpose API 
#ten_a = np.random.normal(size=(3, 4, 5))
                         #axis0 = 3 
                         #axis1 = 4
                         #axis2 = 5 

ten_a = np.array([[[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]],
                   [[21, 22, 23, 24, 25],
                    [26, 27, 28, 29, 30],
                    [31, 32, 33, 34, 35],
                    [36, 37, 38, 39, 40]],
                   [[41, 42, 43, 44, 45],
                    [46, 47, 48, 49, 50],
                    [51, 52, 53, 54, 55],
                    [56, 57, 58, 59, 60]]])

print(f"ten_a shpae {ten_a.shape} \n{ten_a}")
ten_b = np.transpose(ten_a, axes=(0, 1, 2))
ten_c = np.transpose(ten_a, axes=(1, 2, 0))
#ten_d = np.transpose(ten_a, axes=(2, 0, 1))
#ten_e = np.transpose(ten_a, axes=(2, 1, 0))
print("\n========Transpose========")
#print(f"ten_b shpae {ten_b.shape} \n{ten_b}")
print(f"ten_c shpae {ten_c.shape} \n{ten_c}")
#print(f"ten_d shpae {ten_d.shape} \n{ten_d}")
#print(f"ten_e shpae {ten_e.shape} \n{ten_e}")


ten_a shpae (3, 4, 5) 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

========Transpose========
ten_c shpae (4, 5, 3) 
[[[ 1 21 41]
  [ 2 22 42]
  [ 3 23 43]
  [ 4 24 44]
  [ 5 25 45]]

 [[ 6 26 46]
  [ 7 27 47]
  [ 8 28 48]
  [ 9 29 49]
  [10 30 50]]

 [[11 31 51]
  [12 32 52]
  [13 33 53]
  [14 34 54]
  [15 35 55]]

 [[16 36 56]
  [17 37 57]
  [18 38 58]
  [19 39 59]
  [20 40 60]]]


In [27]:
import numpy as np 

ten_a = np.random.normal(size=(3, 4, 5, 6))
ten_b = np.transpose(ten_a, axes=tuple(range(ten_a.ndim))[::-1])