In [6]:
# Tricks for fully connected operations 

import numpy as np 
# scalar case 
vec_x = np.arange(5).reshape(5, )
vec_y = np.arange(2, 6).reshape(4, )
print(f"vec_x : shape {vec_x.shape} \n{vec_x}")
print(f"vec+y : shape {vec_y.shape} \n{vec_y}")

# for x_ in vec_x :
#     for y_ in vec_y : 
#         print(x_ + y_, end="")
#     print()

vec_x : shape (5,) 
[0 1 2 3 4]
vec+y : shape (4,) 
[2 3 4 5]
2345
3456
4567
5678
6789


In [8]:
import numpy as np 

vec_x = np.arange(5)
vec_y = np.arange(2, 6)

print(f"vec_x : {vec_x}")
print(f"vec_y : {vec_y}")

for _x in vec_x : 
    print(_x + vec_y)

vec_x : [0 1 2 3 4]
vec_y : [2 3 4 5]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]
[5 6 7 8]
[6 7 8 9]


In [10]:
import numpy as np 

vec_x = np.arange(5)
vec_y = np.arange(2, 6)

X, Y = np.meshgrid(vec_x, vec_y)

Z = X + Y 

X, Y, Z  = X.T, Y.T, Z.T
print(f"X \n{X}")
print(f"Y \n{Y}")
print(f"Z \n{Z}")


X 
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Y 
[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]
Z 
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [17]:
import numpy as np 

x = np.arange(5)
y = np.arange(2, 6)
print(f"x : shape {x.shape} \n{x}")
print(f"y : shape {y.shape} \n{y}")

X = x.reshape(-1, 1)
print(f"X : shape {X.shape} \n{X}")
Y = y.reshape(1, -1)
print(f"Y shape {Y.shape} \n{Y}")

Z = X + Y 
print(f"Z shape {Z.shape} \n{Z}")
print(f"x[0] + y {Z[0, :]}")
print(f"x[3] + y {Z[3, :]}")


x : shape (5,) 
[0 1 2 3 4]
y : shape (4,) 
[2 3 4 5]
X : shape (5, 1) 
[[0]
 [1]
 [2]
 [3]
 [4]]
Y shape (1, 4) 
[[2 3 4 5]]
Z shape (5, 4) 
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
x[0] + y [2 3 4 5]
x[3] + y [5 6 7 8]


In [23]:
# fully connected operations for vectors  
import numpy as np 
np.random.seed(30)
X = np.random.randint(-5, 5, (4, 2))
Y = np.random.randint(-5, 5, (3, 2))
print(f"X shape {X.shape} \n{X}")
print(f"Y shape {Y.shape} \n{Y}")
print("for loop")

# case for 
for x in X : 
    for y in Y : 
        add = x + y
        print(f"{add}", end="")     
    print()

X shape (4, 2) 
[[ 0  0]
 [-1  2]
 [-3  0]
 [-4 -2]]
Y shape (3, 2) 
[[ 4  2]
 [ 2 -4]
 [-4 -2]]
for loop
[4 2][ 2 -4][-4 -2]
[3 4][ 1 -2][-5  0]
[1 2][-1 -4][-7 -2]
[0 0][-2 -6][-8 -4]


In [37]:
import numpy as np 

X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
print(f"X shape {X.shape}")
print(f"Y shape {Y.shape}")

print("=====expand_dims=====")

X = np.expand_dims(X, axis=1)
Y = np.expand_dims(Y, axis=0)
print(f"X shape {X.shape}")
print(f"Y shape {Y.shape}")
 
Z = X + Y
print(f"Z shape {Z.shape}") 
print(Z)



X shape (4, 2)
Y shape (3, 2)
=====expand_dims=====
X shape (4, 1, 2)
Y shape (1, 3, 2)
Z shape (4, 3, 2)
[[[ 2.51905084 -1.15931942]
  [-3.1641707  -3.15170759]
  [-4.57519177 -0.39726077]]

 [[ 5.34383298  0.72135705]
  [-0.33938856 -1.27103112]
  [-1.75040963  1.4834157 ]]

 [[ 6.75297436 -2.98723175]
  [ 1.06975282 -4.97961992]
  [-0.34126825 -2.22517311]]

 [[ 6.82531224 -0.34585859]
  [ 1.1420907  -2.33824676]
  [-0.26893037  0.41620006]]]
