In [9]:
# Repeating ndarrays 
# numpy repeat(a, repeats, axis=None)
import numpy as np 

# Scalar
scalar_x = 3

rep_scalar = np.repeat(scalar_x, 2)
print(f"rep_scalar : {rep_scalar}") 

# Vector
vec_x = np.array([1, 2, 3])
rep_vec = np.repeat(vec_x, 3)
print(f"rep_vec : {rep_vec}")

# Matrix 
mat_x = np.arange(4).reshape(2, 2)
print(f"mat_x : \n{mat_x}")
rep_mat = np.repeat(mat_x, 3)
print(f"rep_mat : {rep_mat}")

rep_mat_axis0 = np.repeat(mat_x, 3, axis=0)
print(f"rep_mat_axis0 : \n{rep_mat_axis0}")

rep_mat_axis1 = np.repeat(mat_x, 3, axis=1)
print(f"rep_mat_axis1 : \n{rep_mat_axis1}")



rep_scalar : [3 3]
rep_vec : [1 1 1 2 2 2 3 3 3]
mat_x : 
[[0 1]
 [2 3]]
rep_mat : [0 0 0 1 1 1 2 2 2 3 3 3]
rep_mat_axis0 : 
[[0 1]
 [0 1]
 [0 1]
 [2 3]
 [2 3]
 [2 3]]
rep_mat_axis1 : 
[[0 0 0 1 1 1]
 [2 2 2 3 3 3]]


In [18]:
import numpy as np 

mat_a = np.arange(4).reshape(2, 2)
print(f"mat_x : \n{mat_x}")

# the first element is repeated twice
# the second element is repeated once
rep_mat = np.repeat(mat_x, repeats=[2, 1], axis=0)
print(f"rep_mat_axis1 \n{rep_mat}")


# the first element is repeated once
# the second element is repeated twice
rep_mat = np.repeat(mat_x, repeats=[1, 2], axis=0)
print(f"rep_mat_axis1 \n{rep_mat}")


# the first element is repeated twice
# the second element is repeated twice
rep_mat = np.repeat(mat_x, repeats=[2, 2], axis=0)
print(f"rep_mat_axis1 \n{rep_mat}")

mat_x : 
[[0 1]
 [2 3]]
rep_mat_axis1 
[[0 1]
 [0 1]
 [2 3]]
rep_mat_axis1 
[[0 1]
 [2 3]
 [2 3]]
rep_mat_axis1 
[[0 1]
 [0 1]
 [2 3]
 [2 3]]


In [26]:
import numpy as np 

mat_x = np.arange(6).reshape(2, 3)
print(f"mat_x : \n{mat_x}")

# the first element(column) is repeated twice
# the second element(column) is repeated once
# the third element(column) is repeated twice

rep_mat_x = np.repeat(mat_x, repeats =(2, 1, 2), axis=1)
print(f"rep_mat_x : \n{rep_mat_x}")

mat_x : 
[[0 1 2]
 [3 4 5]]
rep_mat_x : 
[[0 0 1 2 2]
 [3 3 4 5 5]]


In [31]:
import numpy as np 

row_vec = np.arange(4).reshape(1, -1)
print(f"row_vec {row_vec.shape} \n {row_vec}")
rep_vec = np.repeat(row_vec, repeats=3, axis=0)
print(f"rep_vec shape {rep_vec.shape}\n{rep_vec}")

col_vec = np.arange(4).reshape(4, 1)
print(f"row_vec {row_vec.shape} \n {row_vec}")
rep_vec = np.repeat(col_vec, repeats=3, axis=1)
print(f"rep_vec shape {rep_vec.shape}\n{rep_vec}")


row_vec (1, 4) 
 [[0 1 2 3]]
rep_vec shape (3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
row_vec (1, 4) 
 [[0 1 2 3]]
rep_vec shape (4, 3)
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
