In [14]:
# Rounding Sorting 
# numpy.sort() : value 
# numpy.argsort() : index 
# ascending 
# descending 

import numpy as np 

np.random.seed(30)
vec_x = np.random.randint(1, 100, (10, ))
print("===========Ascending===========")
print(f"vec_x : {vec_x}")

sort_x = np.sort(vec_x)
print(f"sort_x: {sort_x}")

arg_sort_x = np.argsort(vec_x)
print(f"arg_sort_x: {arg_sort_x}")

print("\n===========Descending===========")

vec_y = np.trunc(np.random.uniform(-10, 10, (10, )))
print(f"vec_y : {vec_y}")

sort_y = np.trunc(np.sort(vec_y)[::-1])
print(f"sort_y: {sort_y}")

arg_sort_y = np.argsort(vec_y)[::-1]
print(f"arg_sort_y: {arg_sort_y}")


===========Ascending===========
vec_x : [38 38 46 46 13 24  3 54 18 47]
sort_x: [ 3 13 18 24 38 38 46 46 47 54]
arg_sort_x: [6 4 8 5 0 1 2 3 9 7]

===========Descending===========
vec_y : [ 9. -5.  1. -1. -7.  0.  0.  5.  8. -8.]
sort_y: [ 9.  8.  5.  1.  0.  0. -1. -5. -7. -8.]
arg_sort_y: [0 8 7 2 6 5 3 1 4 9]


In [18]:
import numpy as np 

pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()
print(f"pred {pred}")

top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]
print(f"top3_pred {top3_pred}")
print(f"top3_indices {top3_indices}")


pred [0.14767878 0.20739409 0.19008932 0.15539084 0.29944697]
top3_pred [0.29944697 0.20739409 0.19008932]
top3_indices [4 1 2]


In [31]:
np.random.seed(30)
mat_x = np.random.randint(0, 100, (4, 5))
print(f"mat_x \n{mat_x}")

print("===========Ascending===========")
sort_asc = np.sort(mat_x, axis=0)
arg_sort_asc = np.argsort(mat_x, axis=0)
# arg_sort_asc = np.argsort(mat_x, axis=1)

print(f"sort_asc \n{sort_asc}")
print(f"arg_sort_asc \n{arg_sort_asc}")

print("\n===========Descending===========")
sort_desc = np.sort(mat_x, axis=0)[::-1, :]
arg_sort_desc = np.argsort(mat_x, axis=0)[::-1, :]
# arg_sort_asc = np.argsort(mat_x, axis=1)

print(f"sort_desc \n{sort_desc}")
print(f"arg_sort_desc \n{arg_sort_desc}")



mat_x 
[[37 37 45 45 12]
 [23  2 53 17 46]
 [ 3 41  7 65 49]
 [45 61 35 18 18]]
===========Ascending===========
sort_asc 
[[ 3  2  7 17 12]
 [23 37 35 18 18]
 [37 41 45 45 46]
 [45 61 53 65 49]]
arg_sort_asc 
[[2 1 2 1 0]
 [1 0 3 3 3]
 [0 2 0 0 1]
 [3 3 1 2 2]]

===========Descending===========
sort_desc 
[[45 61 53 65 49]
 [37 41 45 45 46]
 [23 37 35 18 18]
 [ 3  2  7 17 12]]
arg_sort_desc 
[[3 3 1 2 2]
 [0 2 0 0 1]
 [1 0 3 3 3]
 [2 1 2 1 0]]


In [37]:
import numpy as np 
np.random.seed(30)
score = np.random.randint(0, 100, (5, 3))
print(f"score : \n{score}")
sort_asc = np.sort(score, axis=0)
sort_desc = np.sort(score, axis=0)[::-1, :]
print(f"asc : \n{sort_asc}")
print(f"desc : \n{sort_desc}")

print("\n========Indicies========")
arg_sort_asc = np.argsort(score, axis=0)
arg_sort_desc = np.argsort(score, axis=0)[::-1, :]
print(f"asc : \n{arg_sort_asc}")
print(f"desc : \n{arg_sort_desc}")


score : 
[[37 37 45]
 [45 12 23]
 [ 2 53 17]
 [46  3 41]
 [ 7 65 49]]
asc : 
[[ 2  3 17]
 [ 7 12 23]
 [37 37 41]
 [45 53 45]
 [46 65 49]]
desc : 
[[46 65 49]
 [45 53 45]
 [37 37 41]
 [ 7 12 23]
 [ 2  3 17]]

========Indicies========
asc : 
[[2 3 2]
 [4 1 1]
 [0 0 3]
 [1 2 0]
 [3 4 4]]
desc : 
[[3 4 4]
 [1 2 0]
 [0 0 3]
 [4 1 1]
 [2 3 2]]


In [38]:
import numpy as np 

x =np.random.randint(0, 100, (4, 5))
print(f"x :\n{x}")
sort_ascending = np.sort(x, axis=1)
sort_descending = np.sort(x, axis=1)[:, ::-1]
print(f"sort_ascending :\n{sort_ascending}")
print(f"sort_desscending :\n{sort_descending}")


arg_sort_ascending = np.argsort(x, axis=1)
arg_sort_descending = np.sort(x, axis=1)[:, ::-1]
print(f"arg_sort_ascending :\n{arg_sort_ascending}")
print(f"arg_sort_desscending :\n{arg_sort_descending}")


x :
[[45 61 35 18 18]
 [76 16  6 62 27]
 [46 45 64 62 11]
 [15 23 13 50 33]]
sort_ascending :
[[18 18 35 45 61]
 [ 6 16 27 62 76]
 [11 45 46 62 64]
 [13 15 23 33 50]]
sort_desscending :
[[61 45 35 18 18]
 [76 62 27 16  6]
 [64 62 46 45 11]
 [50 33 23 15 13]]
arg_sort_ascending :
[[3 4 2 0 1]
 [2 1 4 3 0]
 [4 1 0 3 2]
 [2 0 1 4 3]]
arg_sort_desscending :
[[61 45 35 18 18]
 [76 62 27 16  6]
 [64 62 46 45 11]
 [50 33 23 15 13]]


In [41]:
import numpy as np 

scores = np.random.randint(0, 100, (5, 3))
print(f"scores : \n{scores}")
sort = np.sort(scores, axis=1)
argsort = np.argsort(scores, axis = 1)
print(f"sort : \n{sort}")
print(f"argsort : \n{argsort}")

bottom2_scores = sort[:, :2]
bottom2_subject = sort[:, :2]

print(f"bottom2_sort : \n{bottom2_scores}")
print(f"bottom2_argsort : \n{bottom2_subject}")


scores : 
[[93 52 44]
 [61 34 79]
 [43 28 60]
 [76 51 41]
 [56 16 39]]
sort : 
[[44 52 93]
 [34 61 79]
 [28 43 60]
 [41 51 76]
 [16 39 56]]
argsort : 
[[2 1 0]
 [1 0 2]
 [1 0 2]
 [2 1 0]
 [1 2 0]]
bottom2_sort : 
[[44 52]
 [34 61]
 [28 43]
 [41 51]
 [16 39]]
bottom2_argsort : 
[[44 52]
 [34 61]
 [28 43]
 [41 51]
 [16 39]]
