In [42]:
import numpy as np 
# Indexing and Slicing ndarrays 
# Matrix Indexing Slicing 

list_a = [[0, 1, 2], 
          [3, 4, 5], 
          [6, 7, 8]]
# print("list_a[0] : {}".format(list_a[0]))
# print("list_a[1] : {}".format(list_a[1]))
# print("list_a[2] : {}".format(list_a[2]))

# Matrix indexing 
mat_a = np.array(list_a)
# for row in range(len(mat_a)):
#     for col in range(len(mat_a[row])):
#         print("mat_a[{}][{}] : {}".format(row, col, mat_a[row][col]), end=" ")
#     print()

# print()

# print(mat_a)
# print("mat_a[0]: {}".format(mat_a[0]))
# print("mat_a[1]: {}".format(mat_a[1]))
# print("mat_a[2]: {}".format(mat_a[2]))
# print("mat_a[1][2]: {}".format(mat_a[1][2]))
# print("mat_a[1, 2]: {}".format(mat_a[1, 2]))
# print("mat_a[-1, 1]: {}".format(mat_a[-1, 1]))

# Matrix slicing
print("mat_a[:] \n{}".format(mat_a[:]))
print("mat_a[::-1] \n{}".format(mat_a[::-1]))
print("mat_a[1:3:1] \n{}".format(mat_a[1:3:1]))
print("mat_a[2::-1] \n{}".format(mat_a[2::-1]))

# mat_b = np.arange(12).reshape(3, 4)

# for row in range(len(mat_b)):
#     for col in range(len(mat_b[row])):
#         print(f"mat_b[{row}][{col}] : {mat_b[row][col]}", end= " ")
#     print()

# print("mat_b[0, 1: ]: {}".format(mat_b[0, 1:]))
# print("mat_b[::-1]: \n{}".format(mat_b[::-1]))
# print("mat_b[1, :3] \n{}".format(mat_b[1, :3]))
# print("mat_a[2, 1:3] \n{}".format(mat_b[2, 1:3]))

mat_a[:] 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
mat_a[::-1] 
[[6 7 8]
 [3 4 5]
 [0 1 2]]
mat_a[1:3:1] 
[[3 4 5]
 [6 7 8]]
mat_a[2::-1] 
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [55]:
mat_c = np.arange(12).reshape(4, 3)

for row in range(len(mat_c)):
    for col in range(len(mat_c[row])):
        print(f"mat_c[{row}][{col}]: {mat_c[row][col]}" ,end= "")
    print()
print("mat_c[1:, 0]:\n {}".format(mat_c[1:, 0])) 
print("mat_c[:3, 1]:\n {}".format(mat_c[:3, 1])) 
print("mat_c[1:3, 2]:\n {}".format(mat_c[1:3, 2]))       

mat_c[0][0]: 0mat_c[0][1]: 1mat_c[0][2]: 2
mat_c[1][0]: 3mat_c[1][1]: 4mat_c[1][2]: 5
mat_c[2][0]: 6mat_c[2][1]: 7mat_c[2][2]: 8
mat_c[3][0]: 9mat_c[3][1]: 10mat_c[3][2]: 11
mat_c[1:, 0]:
 [3 6 9]
mat_c[:3, 1]:
 [1 4 7]
mat_c[1:3, 2]:
 [5 8]


In [63]:
mat_d = np.arange(16).reshape(4, 4)

for row in range(len(mat_d)):
    for col in range(len(mat_d[row])):
        print(f"mat_d[{row}][{col}] : {mat_d[row][col]}", end="")
    print()
print()
print(f"mat_d[1:3, 1:3] :\n {mat_d[1:3, 1:3]}")
print(f"mat_d[:2, :3] :\n {mat_d[:2, :3]}")
print(f"mat_d[1:, -2:] :\n {mat_d[1:, -2:]}")
print(f"mat_d[-2:, :2] :\n {mat_d[-2:, :2]}")
print(f"mat_d[-2:, :-2] :\n {mat_d[-2:, :-2]}")

mat_d[0][0] : 0mat_d[0][1] : 1mat_d[0][2] : 2mat_d[0][3] : 3
mat_d[1][0] : 4mat_d[1][1] : 5mat_d[1][2] : 6mat_d[1][3] : 7
mat_d[2][0] : 8mat_d[2][1] : 9mat_d[2][2] : 10mat_d[2][3] : 11
mat_d[3][0] : 12mat_d[3][1] : 13mat_d[3][2] : 14mat_d[3][3] : 15

mat_d[1:3, 1:3] :
 [[ 5  6]
 [ 9 10]]
mat_d[:2, :3] :
 [[0 1 2]
 [4 5 6]]
mat_d[1:, -2:] :
 [[ 6  7]
 [10 11]
 [14 15]]
mat_d[-2:, :2] :
 [[ 8  9]
 [12 13]]
mat_d[-2:, :-2] :
 [[ 8  9]
 [12 13]]


In [75]:
import numpy as np 

mat_e = np.arange(16).reshape(4, 4)

for row in range(len(mat_e)):
    for col in range(len(mat_e[row])):
        print(f"[{row}][{col}] : {mat_e[row][col]}", end=" ")
    print()

print(f"mat_e[1:3, 1:3] :\n {mat_e[1:3, 1:3]}")
print(f"mat_e[:2, :3] :\n {mat_e[:2, :3]}")
print(f"mat_e[1:, -3:] :\n {mat_e[1:, -2:]}")
print(f"mat_e[-2:, :-2] :\n {mat_e[-2:, :-2]}")

[0][0] : 0 [0][1] : 1 [0][2] : 2 [0][3] : 3 
[1][0] : 4 [1][1] : 5 [1][2] : 6 [1][3] : 7 
[2][0] : 8 [2][1] : 9 [2][2] : 10 [2][3] : 11 
[3][0] : 12 [3][1] : 13 [3][2] : 14 [3][3] : 15 
mat_e[1:3, 1:3] :
 [[ 5  6]
 [ 9 10]]
mat_e[:2, :3] :
 [[0 1 2]
 [4 5 6]]
mat_e[1:, -3:] :
 [[ 6  7]
 [10 11]
 [14 15]]
mat_e[-2:, :-2] :
 [[ 8  9]
 [12 13]]


In [81]:
import numpy as np 

image = np.arange(9).reshape(3, 3)
print(f"ndarray: \n{image}\n")

horizontal_flip = image[:, ::-1]
print(f"horizotal_flip: \n{horizontal_flip}")

vertical_flip = image[::-1, :]
print(f"vertical_flip \n{vertical_flip}")

rotation = image[::-1, ::-1]
print(f"rotation \n{rotation}")

ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

horizotal_flip: 
[[2 1 0]
 [5 4 3]
 [8 7 6]]
vertical_flip 
[[6 7 8]
 [3 4 5]
 [0 1 2]]
rotation 
[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [87]:
import numpy as np 

mat_f = np.arange(16).reshape((4, 4))
print(mat_f)
print(mat_f[0, :])
print(mat_f[0, ...])
print(mat_f[:, 1])
print(mat_f[..., 1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[0 1 2 3]
[ 1  5  9 13]
[ 1  5  9 13]
