In [4]:
# Rounding and sorting 

import numpy as np 
# around
# round_
# round 

vec_n = np.random.uniform(-5, 5, (5, ))
print(f"vec_n : {vec_n}")

np_around = np.around(vec_n, decimals=2)
np_around_ = np.around(vec_n, decimals=2)
vec_round = vec_n.round(decimals=2)

print(f"np_around : {np_around}")
print(f"np_around_ : {np_around_}")
print(f"vec_round : {vec_round}")



vec_n : [0.71586897 3.07012079 1.04051704 2.50634687 0.11022118]
np_around : [0.72 3.07 1.04 2.51 0.11]
np_around_ : [0.72 3.07 1.04 2.51 0.11]
vec_round : [0.72 3.07 1.04 2.51 0.11]


In [8]:
import numpy as np 

scores = np.random.uniform(0, 100, (100, 5))

means = scores.mean(axis=0)
stds = scores.std(axis = 0)

print(f"means : \n{means}")
print(f"means : \n{stds}")

print(f"means : \n{means.round(decimals=2)}")
print(f"stds : \n{stds.round(2)}")



means : 
[54.33790692 46.37445468 47.65491024 48.99543205 49.82678657]
means : 
[29.08849666 31.45204362 29.90222806 28.9310937  28.77366289]
means : 
[54.34 46.37 47.65 49.   49.83]
stds : 
[29.09 31.45 29.9  28.93 28.77]


In [9]:
import numpy as np 

x = np.random.uniform(-5, 5, (5, ))

np_around = np.around(x)
np_round_ = np.round_(x)
x_round = x.round()

print(f"np_around : \n{np_around}")
print(f"np_round_ : \n{np_round_}")
print(f"x_round : \n{x_round}")


np_around : 
[-4. -5. -4.  4. -3.]
np_round_ : 
[-4. -5. -4.  4. -3.]
x_round : 
[-4. -5. -4.  4. -3.]


In [12]:
import numpy as np 

# ceil 
# floor 
# truncation 
x = np.random.uniform(-5, 5, (5, ))
print(f"x : \n{x}")
x_ceil = np.ceil(x)
x_floor = np.floor(x)
x_trunc = np.trunc(x)

print(f"x_ceil : {x_ceil}")
print(f"x_floor : {x_floor}")
print(f"x_trunc : {x_trunc}")

x : 
[-2.3236733   3.66342656  0.87411055 -2.47147036  2.57633809]
x_ceil : [-2.  4.  1. -2.  3.]
x_floor : [-3.  3.  0. -3.  2.]
x_trunc : [-2.  3.  0. -2.  2.]


In [14]:
import numpy as np 

x = np.random.uniform(-5, 5, (5, ))
print(f"x : \n{x}")
trunc_where = np.where(x >=0, np.floor(x), np.ceil(x))
print(f"trunc_where : {trunc_where}")

x : 
[-1.06477482  3.69918731  2.76904508 -0.49950147 -0.23056052]
trunc_where : [-1.  3.  2. -0. -0.]
