In [31]:
import numpy as np 
# Changing ndarraus chages 

# ndarray.shape -> ndarray.reshape, ndarray.resize, ndarray.flatten, ndarray.raval 
# ndarray.itemsize -> ndarray.astype 

a_vec_np = np.arange(6)

b_mat_np = np.reshape(a_vec_np, (2, 3))
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_mat_np)

a_vec_np = np.arange(24)
b_ten_np = np.reshape(a_vec_np, (2, 3, 4))
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_ten_np)
print(b_ten_np[0][1][3])


print("\n\n")
a_vec_np = np.arange(6)
b_mat_np = a_vec_np.reshape(2, 3)
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_mat_np)

a_vec_np = np.random.randint(0, 100, (100, ))
print(a_vec_np)
b_ten_np = a_vec_np.reshape(20, 5)
print(a_vec_np.reshape((20,5)).mean(axis=0).max())
print(np.max(np.mean(np.reshape(a_vec_np, (20, 5)), axis=0)))

original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]
original ndarray: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
7



original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]
[69  0 31 33 48 31 23  4 43 89 67  2 77 33 99 51 54 19 96 69 73 91 75 90
 87  7 47 43 13 34 11 91 71 15 77 27 19 72 20 74 42  1 14 10 90 54 30 15
 19 53 50 63 84 91 12 40  6 29 53 29 18 80 61 19  1 23 94 59 18 31 27 72
 61 80 89 75 61 17 62 82 48 81  0 16 48 21 22 91 12  4 80 92  9 14 18  7
 17  6 26 66]
55.0
55.0


In [46]:
a = np.random.randint(0, 5, (8, ))
print(a)
print(a.reshape(2, 4))
print(a.reshape((2, 4)).mean(axis=0).max())
print(np.max(np.mean(np.reshape(a, (2, 4)), axis=0)))
print(np.mean(np.reshape(a, (2, 4)), axis=0))

[1 3 4 1 0 1 4 3]
[[1 3 4 1]
 [0 1 4 3]]
4.0
4.0
[0.5 2.  4.  2. ]


In [10]:

# numpy reshape -1 ? 

import numpy as np 

vec_np = np.arange(12)
# row 
mat1_np = vec_np.reshape((2, -1))
mat2_np = vec_np.reshape((3, -1))
mat3_np = vec_np.reshape((4, -1))
mat4_np = vec_np.reshape((6, -1))
# print(mat1_np, "\n", (mat1_np.shape))
# print(mat2_np, "\n", (mat2_np.shape))
# print(mat3_np, "\n", (mat3_np.shape))
# print(mat4_np, "\n", (mat4_np.shape))

# column 
mat1_np = vec_np.reshape((-1, 2))
mat2_np = vec_np.reshape((-1, 3))
mat3_np = vec_np.reshape((-1, 4))
mat4_np = vec_np.reshape((-1, 6))
# print(mat1_np, "\n", (mat1_np.shape))
# print(mat2_np, "\n", (mat2_np.shape))
# print(mat3_np, "\n", (mat3_np.shape))
# print(mat4_np, "\n", (mat4_np.shape))

ten1_np = vec_np.reshape(2, 3, -1)
ten2_np = vec_np.reshape(2, 6, -1)
print(ten2_np)

mat_ran_np = np.random.randint(0, 10, size=(2, 2))
# print(mat_ran_np)

row_vec_np = vec_np.reshape(1, -1)
print(row_vec_np.shape)
print(row_vec_np)

vec_a_np = np.arange(16)
print(vec_a_np)

vec_b_np = np.resize(vec_a_np, (2, 2, 3))
print(vec_b_np)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]
(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
# Changing ndarrays shape 
# numpy.resize(a, new_shape)
import numpy as np 

vec_a = np.arange(6)
print(vec_a)
mat_b = np.reshape(vec_a, (3, 2))
print(mat_b)
mat_c = np.resize(vec_a, (3, 4))
print(mat_c)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]


In [15]:
# Changing ndarrays shape 
# ndarray.resize 
vec_a = np.arange(9)
print(vec_a)
vec_b = vec_a.resize((3, 4))
print(vec_b)
print(vec_a)

[0 1 2 3 4 5 6 7 8]
None
[[0 1 2 3]
 [4 5 6 7]
 [8 0 0 0]]


In [17]:
# Changing ndarrays shapes 
# flatten() 

original_vec = np.arange(9)
print(original_vec, "\n")
new_mat = original_vec.reshape(3, 3)
print(new_mat, "\n")
new_vec = new_mat.flatten()
print(new_vec, "\n")

M = np.arange(27)
N = M.reshape(3, 3, 3)
O = N.flatten()

print(M, "\n")
print(N, "\n")
print(O, "\n")


[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 



In [30]:
# Memory Optimization 
# copy and view of ndarrays
# copy <-> View 
import copy 
import numpy as np 
original_arr = np.arange(5)
view_arr = original_arr.view()
print(original_arr)
print(view_arr)
original_arr += 10
print(original_arr)
print(view_arr)

a = np.arange(5)
b = a[0:3]
print(a)
print(b)
b[...] = 10
print(a)
print(b)

a = np.arange(5)
b = copy.deepcopy(a)
print(a)
print(b)

b[...] =10 

print(a)
print(b)

np_a = np.arange(5)
np_b = np_a.copy()
np_c = np_a.view()
np_d = np_a[0:3]

print(np_b.base is np_a)
print(np_c.base is np_a)
print(np_d.base is np_a)

[0 1 2 3 4]
[0 1 2 3 4]
[10 11 12 13 14]
[10 11 12 13 14]
[0 1 2 3 4]
[0 1 2]
[10 10 10  3  4]
[10 10 10]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[10 10 10 10 10]
False
True
True


In [42]:
origianl_a = np.arange(4)
reshape_b = origianl_a.reshape((2, 2))
reshape_b[0, 0] =100

print(reshape_b.base is origianl_a ,"\n")
print(origianl_a)
print(reshape_b)
print("\n\n")

origianl_a = np.arange(6)
resize_b = np.resize(origianl_a, (4, 2))
resize_b[0, 1] =100

print(resize_b.base is origianl_a ,"\n")
print(origianl_a)
print(resize_b)

True 

[100   1   2   3]
[[100   1]
 [  2   3]]



False 

[0 1 2 3 4 5]
[[  0 100]
 [  2   3]
 [  4   5]
 [  0   1]]


In [46]:
import numpy as np 
from numpy.random import randint
a = randint(0, 10, (2, 5))
b = a.ravel()
b[0] = -10 
print(b.base is a, "\n")
print(a)
print(b)
print("\n")

a = randint(0, 10, (2, 3))
b = a.flatten()
b[0] = -10
print(b.base is a, "\n")
print(a)
print(b)

True 

[[-10   6   2   2   3]
 [  9   6   9   3   0]]
[-10   6   2   2   3   9   6   9   3   0]


False 

[[2 6 8]
 [1 6 7]]
[-10   6   8   1   6   7]
