In [18]:
import numpy as np 
# Element-wise Operations and Broadcasting 

np.random.seed(30)
a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))

print("a : ", a)
print("b : ", b)
print("a + b   : ", (a + b))
print("a - b   : ", (a - b))
print("a * b   : ", (a *  b))
print("a / b   : ", (a /  b))
print("a // b  : ", (a // b))
print("a % b   : ", (a %  b))
print("a ** b  : ", (a ** b))
print("\n\n")
print("a + b   : ", a.__add__(b))
print("a - b   : ", a.__sub__(b))
print("a * b   : ", a.__mul__(b))
print("a / b   : ", a.__truediv__(b))
print("a // b  : ", a.__floordiv__(b))
print("a % b   : ", a.__mod__(b))
print("a ** b  : ", a.__pow__(b))

print("a > b : " , a > b)
print("a > b : " , a >= b)
print("a > b : " , a < b)
print("a > b : " , a <= b)
print("a == b : " , a == b)
print("a != b : " , a != b)

mat_np1 = np.random.randint(1, 5, (2, 3))
mat_np2 = np.random.randint(1, 5, (2, 3))

print("mat_np1 :\n" , mat_np1)
print("mat_np2 :\n" , mat_np2)

print("mat_np1 + mat_np2 :\n", mat_np1 + mat_np2)
print("mat_np1 - mat_np2 :\n", mat_np1 - mat_np2) 

print("mat_np1 > mat_np2 :\n", mat_np1 > mat_np2)
print("mat_np1 >= mat_np2 :\n", mat_np1 >= mat_np2)

a = np.array(5)
mask = np.array([0, 1, 0, 1, 0])

print("input :", a)
print("mask :", mask)
print("output :", a*mask)


a :  [2 2 2 2 1]
b :  [1 4 3 2 4]
a + b   :  [3 6 5 4 5]
a - b   :  [ 1 -2 -1  0 -3]
a * b   :  [2 8 6 4 4]
a / b   :  [2.         0.5        0.66666667 1.         0.25      ]
a // b  :  [2 0 0 1 0]
a % b   :  [0 2 2 0 1]
a ** b  :  [ 2 16  8  4  1]



a + b   :  [3 6 5 4 5]
a - b   :  [ 1 -2 -1  0 -3]
a * b   :  [2 8 6 4 4]
a / b   :  [2.         0.5        0.66666667 1.         0.25      ]
a // b  :  [2 0 0 1 0]
a % b   :  [0 2 2 0 1]
a ** b  :  [ 2 16  8  4  1]
a > b :  [ True False False False False]
a > b :  [ True False False  True False]
a > b :  [False  True  True False  True]
a > b :  [False  True  True  True  True]
a == b :  [False False False  True False]
a != b :  [ True  True  True False  True]
mat_np1 :
 [[2 3 4]
 [2 4 4]]
mat_np2 :
 [[2 2 2]
 [2 4 3]]
mat_np1 + mat_np2 :
 [[4 5 6]
 [4 8 7]]
mat_np1 - mat_np2 :
 [[0 1 2]
 [0 0 1]]
mat_np1 > mat_np2 :
 [[False  True  True]
 [False False  True]]
mat_np1 >= mat_np2 :
 [[ True  True  True]
 [ True  True  True]]
input : 5
mask