In [13]:
# Repeating ndarrays 
# Application Repetition 
import numpy as np 

mat_x = np.arange(4*3).reshape(4, 3)
print(f"mat_x shape{mat_x.shape} \n{mat_x}")
sum_mat = mat_x.sum(axis=0, keepdims=True)
print(sum_mat)

rep_mat = sum_mat.repeat(repeats=3, axis=0)
print(rep_mat)

print(rep_mat.transpose())

mat_x shape(4, 3) 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[18 22 26]]
[[18 22 26]
 [18 22 26]
 [18 22 26]]
[[18 18 18]
 [22 22 22]
 [26 26 26]]


In [16]:
import numpy as np 

mat_x = np.arange(4*3).reshape(4, 3)
print(f"mat_x shape {mat_x.shape}\n{mat_x}")

mat_y = mat_x.sum(0, keepdims=True).repeat(3, 0).T
print(f"mat_y shape {mat_y.shape} \n{mat_y}")

mat_x shape (4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
mat_y shape (3, 3) 
[[18 18 18]
 [22 22 22]
 [26 26 26]]


In [21]:
import numpy as np 
mat_x = np.arange(12).reshape(4, 3)
print(f"max_x shape {mat_x.shape} \n{mat_x}")

mat_x = mat_x.sum(1, keepdims=True).repeat(2, 1).T
print(mat_x)

max_x shape (4, 3) 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3 12 21 30]
 [ 3 12 21 30]]
