In [30]:
# Merging ndarrays using np.concatenate

import numpy as np 

vec_a = np.random.randint(0, 10, (3, ))
vec_b = np.random.randint(0, 10, (4, ))
print(f"vec_a shape : {vec_a.shape} \n {vec_a}")
print(f"vec_b shape : {vec_b.shape} \n {vec_b}")
# case two vector 
concat = np.concatenate((vec_a, vec_b))
print(f"concat : shape {concat.shape} \n{concat}") 

# case three vector 
vec_c = np.random.randint(0, 10, (4, ))
vec_d = np.random.randint(0, 10, (4, ))
vec_e = np.random.randint(0, 10, (4, ))
print(f"vec_a shape {vec_c.shape} {vec_c}")
print(f"vec_a shape {vec_d.shape} {vec_d}")
print(f"vec_a shape {vec_e.shape} {vec_e}")

concat = np.concatenate([vec_c, vec_d, vec_e], axis=0)
print(f"concat : shape {concat.shape} length {len(concat)} \n{concat}")

vec_a shape : (3,) 
 [8 0 4]
vec_b shape : (4,) 
 [4 6 0 0]
concat : shape (7,) 
[8 0 4 4 6 0 0]
vec_a shape (4,) [6 6 6 0]
vec_a shape (4,) [2 4 4 6]
vec_a shape (4,) [9 5 8 2]
concat : shape (12,) length 12 
[6 6 6 0 2 4 4 6 9 5 8 2]


In [23]:
import numpy as np 

# mat_a = np.array([[1, 2, 3]
#                   [4, 5, 6],
#                   [7, 8, ]])

# case matrix  
mat_a = np.random.randint(0, 10, (1, 3))
mat_b = np.random.randint(0, 10, (1, 3))
print(f"mat_a shape{mat_a.shape} \n{mat_a}")
print(f"mat_b shape{mat_b.shape} \n{mat_b}")

concat_axis0 = np.concatenate([mat_a, mat_b], axis=0)
concat_axis1 = np.concatenate([mat_a, mat_b], axis=1)
concat_axis_n1 = np.concatenate([mat_a, mat_b], axis=-1)
print(f"concat_mat shape {concat_axis0.shape} \n {concat_axis0}")
print(f"concat_mat shape {concat_axis1.shape} \n {concat_axis1}")
print(f"concat_mat shape {concat_axis_n1.shape} \n {concat_axis_n1}")

mat_a shape(1, 3) 
[[5 3 8]]
mat_b shape(1, 3) 
[[5 9 3]]
concat_mat shape (2, 3) 
 [[5 3 8]
 [5 9 3]]
concat_mat shape (1, 6) 
 [[5 3 8 5 9 3]]
concat_mat shape (1, 6) 
 [[5 3 8 5 9 3]]


In [34]:
import numpy as np 

# case matrix 
mat_a = np.random.randint(1, 3, (3, 4))
mat_b = np.random.randint(1, 3, (3, 2))

print(f"mat_a shape{mat_a.shape} \n{mat_a}")
print(f"mat_b shape{mat_b.shape} \n{mat_b}")
concat = np.concatenate([mat_a, mat_b], axis=1)

print(f"concat shape {concat.shape} \n {concat}")

mat_a shape(3, 4) 
[[2 2 1 1]
 [2 2 2 1]
 [1 1 1 1]]
mat_b shape(3, 2) 
[[1 2]
 [2 2]
 [2 1]]
concat shape (3, 6) 
 [[2 2 1 1 1 2]
 [2 2 2 1 2 2]
 [1 1 1 1 2 1]]


In [38]:
import numpy as np 

ten_a = np.random.randint(0, 10, (3, 4, 5))
ten_b = np.random.randint(0, 10, (10, 4, 5))
ten_c = np.random.randint(0, 10, (3, 10, 5))
print(f"ten_a {ten_a.shape} \n {ten_a}")
print(f"ten_b {ten_b.shape} \n {ten_b}")

concat_axis0 = np.concatenate([ten_a, ten_b], axis=0)
print(f"concat_axis0 {concat_axis0.shape}")

concat_axis1 = np.concatenate([ten_a, ten_c], axis=1)
print(f"concat_axis1 shape{concat_axis1.shape}")

ten_a (3, 4, 5) 
 [[[8 4 4 1 8]
  [4 8 2 5 3]
  [4 0 8 7 0]
  [9 9 4 6 9]]

 [[0 8 3 4 7]
  [3 1 0 1 0]
  [3 4 6 7 9]
  [7 0 7 3 4]]

 [[3 6 9 5 2]
  [2 4 4 0 9]
  [1 7 8 4 3]
  [2 7 3 6 9]]]
ten_b (10, 4, 5) 
 [[[5 7 9 5 7]
  [4 9 5 6 5]
  [0 2 2 8 8]
  [2 5 9 3 6]]

 [[0 8 0 0 8]
  [7 2 0 7 9]
  [6 4 4 0 9]
  [9 5 2 0 5]]

 [[9 1 9 6 7]
  [0 9 7 0 7]
  [7 0 7 7 9]
  [2 1 7 3 4]]

 [[6 6 9 3 6]
  [7 9 5 6 9]
  [9 2 1 0 5]
  [5 6 1 6 1]]

 [[1 2 8 4 5]
  [7 5 7 3 8]
  [3 3 1 2 3]
  [7 2 9 8 2]]

 [[9 9 6 7 8]
  [2 0 6 1 4]
  [5 3 9 7 7]
  [1 6 8 2 1]]

 [[7 6 2 3 2]
  [5 7 7 4 3]
  [4 9 0 0 8]
  [9 2 5 8 4]]

 [[3 7 8 4 2]
  [3 5 9 3 7]
  [4 5 4 3 0]
  [4 8 2 1 4]]

 [[1 8 2 0 4]
  [4 7 8 2 7]
  [6 7 0 1 4]
  [4 7 1 1 1]]

 [[2 6 8 9 8]
  [2 9 6 4 7]
  [8 8 9 0 0]
  [6 5 8 7 5]]]
concat_axis0 (13, 4, 5)
concat_axis1 shape(3, 14, 5)


In [2]:
import numpy as np 

dataset_tmp = list()

# vstack 
for iter in range(100):
    data_sample = np.random.uniform(0, 5, (1, 4))
    dataset_tmp.append(data_sample)

concat_axis0 = np.concatenate(dataset_tmp, axis=0)
print(f"concat_axis0 shape {concat_axis0.shape}")

# hstack 
dataset_tmp = list()
for iter in range(100):
    data_sample = np.random.uniform(0, 5, (4, 1))
    dataset_tmp.append(data_sample)

concat_axis1 = np.concatenate(dataset_tmp, axis=1)
print(f"concat_axis1 shape {concat_axis1.shape}")
    

concat_axis0 shape (100, 4)
concat_axis1 shape (4, 100)


In [5]:
import numpy as np 
# Using dstack 
R = np.random.randint(0, 10, (100, 200))
G = np.random.randint(0, 10, size=R.shape)
B = np.random.randint(0, 10, size=R.shape)

image = np.dstack([R, G, B])

print(image.shape)

(100, 200, 3)


In [7]:
import numpy as np 

a = np.random.randint(0, 10, (100, 200, 3))
b = np.random.randint(0, 10, size = a.shape)
c = np.random.randint(0, 10, size = a.shape)

d = np.dstack([a, b, c])
print(f"d shape {d.shape})")

d shape (100, 200, 9))


In [12]:
import numpy as np 
# Using stack 
mat_a = np.random.randint(0, 10, (100, 200))
mat_b = np.random.randint(0, 10, (100, 200))
mat_c = np.random.randint(0, 10, (100, 200))

print(f"ndim 2: {np.stack([a, b, c]).shape}")

ten_a = np.random.randint(0, 10, (100, 200, 300))
ten_b = np.random.randint(0, 10, size=ten_a.shape)
ten_c = np.random.randint(0, 10, size=ten_a.shape)

print(f"ndim 3 : {np.stack([ten_a, ten_b, ten_c]).shape}")



ndim 2: (3, 100, 200)
ndim 3 : (3, 100, 200, 300)


In [17]:
import numpy as np 

ten_a = np.random.randint(0, 10, (100, 200, 300))
ten_b = np.random.randint(0, 10, (100, 200, 300))
ten_c = np.random.randint(0, 10, (100, 200, 300))

print(f"axis = 0 : {np.stack((ten_a, ten_b, ten_c), axis=0).shape}")
print(f"axis = 1 : {np.stack((ten_a, ten_b, ten_c), axis=1).shape}")
print(f"axis = 2 : {np.stack((ten_a, ten_b, ten_c), axis=2).shape}")
print(f"axis = 3 : {np.stack((ten_a, ten_b, ten_c), axis=3).shape}")


axis = 0 : (3, 100, 200, 300)
axis = 1 : (100, 3, 200, 300)
axis = 2 : (100, 200, 3, 300)
axis = 3 : (100, 200, 300, 3)
