In [11]:
# Removing Dummy Dimensions 

import numpy as np 

mat_a =np.ones(shape=(1, 10))
print(f"mat_a shape {mat_a.shape} \n {mat_a}")
vec_a = mat_a.reshape((10, ))
vec_b = mat_a.reshape((-1, ))
vec_d = mat_a.flatten()

# print(f"vec_a shape {vec_a.shape} \n {vec_a}")
# print(f"vec_b shape {vec_b.shape} \n {vec_b}")
# print(f"vec_d shape {vec_d.shape} \n {vec_d}")
print(f"vec_a shape {vec_a.shape}")
print(f"vec_b shape {vec_b.shape}")
print(f"vec_d shape {vec_d.shape}")


mat_a shape (1, 10) 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
vec_a shape (10,)
vec_b shape (10,)
vec_d shape (10,)


In [18]:
import numpy as np 

ten_a= np.ones(shape=(1, 3, 4))
ten_b= np.ones(shape=(4, 3, 1))

print(f"ten_a {ten_a.shape} \n{ten_a}")
# print(f"ten_b {ten_b.shape} \n{ten_b}")

c = ten_a.reshape(*ten_a.shape[1:])
print(*ten_a.shape[1:])
print(f"c {c.shape} \n{c}")


ten_a (1, 3, 4) 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 4
c (3, 4) 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
import numpy as np 

mat_a = np.arange(9).reshape(3, 3)
print(f"mat_a shape {mat_a.shape} \n{mat_a}")
vec_row, vec_col = mat_a[1, :], mat_a[:, 1]

print(f"vec_row shape {vec_row.shape} {vec_row}")
print(f"vec_col shape {vec_col.shape} {vec_col}")

mat_a shape (3, 3) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
vec_row shape (3,) [3 4 5]
vec_col shape (3,) [1 4 7]


In [24]:
import numpy as np 

ten_a = np.ones(shape=(1, 3, 4))
print(f"ten_a shape {ten_a.shape} : \n{ten_a}")
mat_c = np.squeeze(ten_a)
print(f"mat_c shape {mat_c.shape} : \n{mat_c}")
mat_d = ten_a.squeeze()
print(f"mat_d shape {mat_d.shape} : \n{mat_d}")


ten_a shape (1, 3, 4) : 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
mat_c shape (3, 4) : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
mat_d shape (3, 4) : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
ten_a = np.ones(shape=(1, 1, 4, 1, 3, 1))
print(f"ten_a shape {ten_a.shape} \n{ten_a}")

c = np.squeeze(ten_a)
print(f"c shape {c.shape} \n{c}")


ten_a shape (1, 1, 4, 1, 3, 1) 
[[[[[[1.]
     [1.]
     [1.]]]


   [[[1.]
     [1.]
     [1.]]]


   [[[1.]
     [1.]
     [1.]]]


   [[[1.]
     [1.]
     [1.]]]]]]
c shape (4, 3) 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
