In [3]:
# Indexing with int ndarrays 
# Indexing and Slicing bool ndarrays 
import numpy as np 
np.random.seed(30)
vec_a = np.arange(5)
print(f"vec_a :\n {vec_a}")

b_indices = np.array([True, False, True, False, True])
print(f"b_indices : \n {b_indices}")
 
 # return True 
print(f"vec_a[{b_indices}] :\n {vec_a[b_indices]}")


vec_a :
 [0 1 2 3 4]
b_indices : 
 [ True False  True False  True]
vec_a[[ True False  True False  True]] :
 [0 2 4]


In [10]:
np.random.seed(30)
vec_b = np.random.randint(0, 20, (10, ))
print(f"vec_b : \n {vec_b}")

b_indices = vec_b % 2 ==0 
print(f"b_indices : {b_indices}")

print(f"vec_b[{b_indices} : {vec_b[b_indices]}]")

vec_b : 
 [ 5  5 13 13 12  2 17 14  3  9]
b_indices : [False False False False  True  True False  True False False]
vec_b[[False False False False  True  True False  True False False] : [12  2 14]]


In [21]:
np.random.seed(30)
mat_a = np.random.randint(0, 20, size=(2, 2))
print(f"mat_a : shape  : {mat_a.shape} ndim :{mat_a.ndim} \n {mat_a}")

b_indices = np.array([[True,  False], [False, True]])
print(f"b_indices : {b_indices}")

print(f"mat_a[{b_indices} : {mat_a[b_indices]}")


mat_a : shape  : (2, 2) ndim :2 
 [[ 5  5]
 [13 13]]
b_indices : [[ True False]
 [False  True]]
mat_a[[[ True False]
 [False  True]] : [ 5 13]


In [29]:
np.random.seed(30)

mat_b = np.random.randint(0, 20, (3, 4))
print(f"mat_b : shape {mat_b.shape}: ndim : {mat_b.ndim}  \n {mat_b}")

b_indices = mat_b > 10

print(f"b_indices : shpae {b_indices.shape} ndim : {b_indices.ndim} \n {b_indices}")

print(f"mat_b[{b_indices}] : \n {mat_b[b_indices]}")

mat_b : shape (3, 4): ndim : 2  
 [[ 5  5 13 13]
 [12  2 17 14]
 [ 3  9  7  1]]
b_indices : shpae (3, 4) ndim : 2 
 [[False False  True  True]
 [ True False  True  True]
 [False False False False]]
mat_b[[[False False  True  True]
 [ True False  True  True]
 [False False False False]]] : 
 [13 13 12 17 14]


In [36]:
import numpy as np 

vec_a = np.array([True, False, True, False])
print(f"vec_a shape : {vec_a.shape} ndim :  {vec_a.ndim} \n {vec_a}")

tup_nonzero = np.nonzero(vec_a)
tup_where = np.where(vec_a)
print(f"tup_nozero type: {type(tup_nonzero)} \n{tup_nonzero}")
print(f"tup_where type : {type(tup_where)} \n{tup_where}")

vec_a shape : (4,) ndim :  1 
 [ True False  True False]
tup_nozero type: <class 'tuple'> 
(array([0, 2], dtype=int64),)
tup_where type : <class 'tuple'> 
(array([0, 2], dtype=int64),)


In [46]:
import numpy as np
np.random.seed(30)
# Matrix 
mat_c = np.array([[1, 0, 7], 
                  [8, 1, 0], 
                  [1, 0, 0]])
print(f"mat_c shape : {mat_c.shape} ndim : {mat_c.ndim} : \n {mat_c}")
tup_nonzero = np.nonzero(mat_c)
trans_nonzero = np.transpose(np.nonzero(mat_c)) 
print(f"tup_nonzero type :{type(tup_nonzero)} : {tup_nonzero}")
print(f"trans_nonzero : {trans_nonzero}")

print("="*30)
# Tensor 
ten_a = np.array([[[True, False, True], 
                   [True, False, True]],
                  [[False, True, False],
                   [True, False, True]]])

print(f"ten_a shape : {ten_a.shape} ndim : {ten_a.ndim} : \n {ten_a}")

tup_nonzero = np.nonzero(ten_a)
trans_nonzero = np.transpose(np.nonzero(ten_a))

print(f"tup_nonzero type :{type(tup_nonzero)} : {tup_nonzero}")
print(f"trans_nonzero : {trans_nonzero}")


mat_c shape : (3, 3) ndim : 2 : 
 [[1 0 7]
 [8 1 0]
 [1 0 0]]
tup_nonzero type :<class 'tuple'> : (array([0, 0, 1, 1, 2], dtype=int64), array([0, 2, 0, 1, 0], dtype=int64))
trans_nonzero : [[0 0]
 [0 2]
 [1 0]
 [1 1]
 [2 0]]
ten_a shape : (2, 2, 3) ndim : 3 : 
 [[[ True False  True]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]]
tup_nonzero type :<class 'tuple'> : (array([0, 0, 0, 0, 1, 1, 1], dtype=int64), array([0, 0, 1, 1, 0, 1, 1], dtype=int64), array([0, 2, 0, 2, 1, 0, 2], dtype=int64))
trans_nonzero : [[0 0 0]
 [0 0 2]
 [0 1 0]
 [0 1 2]
 [1 0 1]
 [1 1 0]
 [1 1 2]]


In [50]:
import numpy as np 

np.random.seed(30)
mat_a = np.random.randint(-2, 3, size=(3, 3))
print(f"mat_a shape : {mat_a.shape} ndim : {mat_a.ndim}\n {mat_a}")

u_nonzero = mat_a[np.nonzero(mat_a)]
u_where = mat_a[np.where(mat_a)]
u_bool = mat_a[mat_a!=0]
print(f"u_nonzero shape : {u_nonzero.shape} ndim : {u_nonzero.ndim}\n {u_nonzero}")
print(f"u_where shape : {u_where.shape} ndim : {u_where.ndim}\n {u_where}")
print(f"u_bool shape : {u_bool.shape} ndim : {u_bool.ndim}\n {u_bool}")


mat_a shape : (3, 3) ndim : 2
 [[ 2  2  0]
 [ 1 -1  1]
 [-1 -1 -1]]
u_nonzero shape : (8,) ndim : 1
 [ 2  2  1 -1  1 -1 -1 -1]
u_where shape : (8,) ndim : 1
 [ 2  2  1 -1  1 -1 -1 -1]
u_bool shape : (8,) ndim : 1
 [ 2  2  1 -1  1 -1 -1 -1]
