In [12]:
# Indexing with int ndarrays 
# Indexing and Slicing Vector ndarrays 
import numpy as np 

vec_a = np.arange(10)
print(f"ndarray:\n{vec_a}\n")

indices = np.array([0, 3, 4])
print(f"vec_a[0, 3, 4] : {vec_a[indices]}")

indices = np.array([0, 0, 5, 5])
print(f"vec_a[0, 0, 5, 5] : {vec_a[indices]}")

indices1 = np.array([[2, 1, 3], [5, 8, 9]])
print(indices1.shape)
print(f"vec_a[[2, 1, 3], [5, 8, 9]] :\n{vec_a[indices1]}")

ndarray:
[0 1 2 3 4 5 6 7 8 9]

vec_a[0, 3, 4] : [0 3 4]
vec_a[0, 0, 5, 5] : [0 0 5 5]
(2, 3)
vec_a[[2, 1, 3], [5, 8, 9]] :
[[2 1 3]
 [5 8 9]]


In [20]:
np.random.seed(30)
vec_a = np.random.randint(0, 20, (10, ))
print(f"ndarray:\n{vec_a}\n")

indices = np.random.randint(0, 10, size=(2, 3, 4))
print(indices.shape)
print(indices)
print(vec_a[indices])
# 14, 14, 5, 5
# 13, 13, 13, 12
 

ndarray:
[ 5  5 13 13 12  2 17 14  3  9]

(2, 3, 4)
[[[7 7 1 1]
  [3 2 2 4]
  [4 6 0 6]]

 [[0 7 4 2]
  [1 7 1 9]
  [8 5 9 7]]]
[[[14 14  5  5]
  [13 13 13 12]
  [12 17  5 17]]

 [[ 5 14 12 13]
  [ 5 14  5  9]
  [ 3  2  9 14]]]


In [24]:
mat_a = np.arange(12).reshape(3, 4)
print(f"ndarray: \n{mat_a}\n")
indices = np.array([0, 2])
print(mat_a[indices])

indices = np.array([0, 0, 1, 1, 2, 2])
print(mat_a[indices])

indices = np.array([[0, 1, 2], 
                    [-3, -2, -1]])

print(f"mat_a[[0, 1, 2], [-3, -2, -1]] :\n{mat_a[indices]}")

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]
mat_a[[0, 1, 2], [-3, -2, -1]] :
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [31]:
mat_a = np.arange(12).reshape((3, 4))
print(f"ndarray :\{mat_a}")
indices0, indices1 = np.array([0]), np.array([0])
print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )

indices0, indices1 = np.array([1]), np.array([1])
print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )

indices0, indices1 = np.array([-1]), np.array([0])
print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )


indices0, indices1 = np.array([-1]), np.array([-1])
print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )

ndarray :\[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat_a[[0], [0]] :
 [0]
mat_a[[1], [1]] :
 [5]
mat_a[[-1], [0]] :
 [8]
mat_a[[-1], [-1]] :
 [11]


In [37]:
mat_a = np.arange(12).reshape(3, 4)
print(f"ndarray : \n{mat_a}")

indices0, indices1 = np.array([0, 1, 2]), np.array([1, 2, 3])

for idx0, idx1 in zip(indices0, indices1):
    print(f"({idx0}, {idx1})")

print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )


indices0 = np.array([[0, 1, 2], [0, 1, 2]])
indices1 = np.array([[0, 1, 2], [1, 2, 3]])

for row0, row1 in zip(indices0, indices1):
  for col0, col1 in zip(row0, row1):
      print(f"({col0}, {col1})", end= " ")
  print()  

print(f"mat_a[{indices0}, {indices1}] :\n {mat_a[indices0, indices1]}" )


ndarray : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(0, 1)
(1, 2)
(2, 3)
mat_a[[0 1 2], [1 2 3]] :
 [ 1  6 11]
(0, 0) (1, 1) (2, 2) 
(0, 1) (1, 2) (2, 3) 
mat_a[[[0 1 2]
 [0 1 2]], [[0 1 2]
 [1 2 3]]] :
 [[ 0  5 10]
 [ 1  6 11]]
