In [11]:
import numpy as np 

# Numpy Sum, Prod, Diff, and Statistics 

# numpy.cumsum()
# ndarray.cumsum()

vec_a = np.arange(5)
print(f"vec_a : \n {vec_a}")
cumsum = np.cumsum(vec_a)
print(f"np.cumsum(vec_a) : {np.cumsum(vec_a)}")
print(f"vec_a.cumsum() {vec_a.cumsum()}" )


mat_a = np.arange(9).reshape(3, 3)
print(f"mat_a shape {mat_a.shape}, ndim : {mat_a.ndim} \n{mat_a}")
mat_cumsum = mat_a.cumsum(axis=1)
mat_cumsum = mat_a.cumsum().reshape(3, 3)

print(f"mat_cumsum \n{mat_cumsum}")



vec_a : 
 [0 1 2 3 4]
np.cumsum(vec_a) : [ 0  1  3  6 10]
vec_a.cumsum() [ 0  1  3  6 10]
mat_a shape (3, 3), ndim : 2 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
mat_cumsum 
[[ 0  1  3]
 [ 6 10 15]
 [21 28 36]]


In [20]:
ten_a = np.arange(24).reshape((2, 3, 4))
print(f"ten_a  shape {ten_a.shape} ndim {ten_a.ndim} \n{ten_a}")
vec_cumsum = ten_a.cumsum()
ten_cumsun = ten_a.cumsum().reshape(2, 3, 4)

print(vec_cumsum)
print(ten_cumsun)

ten_a  shape (2, 3, 4) ndim 3 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276]
[[[  0   1   3   6]
  [ 10  15  21  28]
  [ 36  45  55  66]]

 [[ 78  91 105 120]
  [136 153 171 190]
  [210 231 253 276]]]


In [24]:
mat_b = np.arange(3 * 4).reshape(3, 4)
print(f"mat_b shape {mat_b.shape} ndim : {mat_b.ndim} \n {mat_b}")

mat_cumsum = np.cumsum(mat_b, axis=0)
print(mat_cumsum)

mat_b shape (3, 4) ndim : 2 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [28]:
import numpy as np 

vec_a = np.arange(1, 5)
print(f"vec_a shape {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")

prod_vec= np.prod(vec_a)
print(prod_vec) 
cumpord_vec = np.cumprod(vec_a)
print(cumpord_vec)

vec_a shape (4,) ndim : 1 
 [1 2 3 4]
24
[ 1  2  6 24]


In [33]:
mat_a = np.arange(1, 1+12).reshape((3, 4))
print(f"ndarray {mat_a.shape} \n{mat_a}")

vec_prod = np.prod(mat_a, axis=0)
mat_cumsum = np.cumprod(mat_a, axis=0)

print(f"prod(axis=0) :\n {vec_prod}")
print(f"prod(axis=0) :\n {mat_cumsum}")

ndarray (3, 4) 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
prod(axis=0) :
 [ 45 120 231 384]
prod(axis=0) :
 [[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]


In [40]:
import numpy as np 
# numpy diff
np.random.seed(30) 
vec_a = np.random.randint(0, 10, (5, ))
print(f"vec_a : shape : {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")

vec_diff = np.diff(vec_a)
print(f"vec_dff \n{vec_diff}")


vec_a : shape : (5,) ndim : 1 
 [5 5 4 7 2]
vec_dff 
[ 0 -1  3 -5]


In [42]:
import numpy as np 
np.random.seed(30)

mat_a = np.random.randint(1, 10, (4, 4))
print(f"mat_a shape {mat_a.shape} \n {mat_a}")

mat_diff = np.diff(mat_a, axis=0)
print(f"diff: shape {mat_diff.shape} \n {mat_diff} ")

mat_a shape (4, 4) 
 [[6 6 5 8]
 [3 6 2 4]
 [8 8 2 2]
 [4 3 3 5]]
diff: shape (3, 4) 
 [[-3  0 -3 -4]
 [ 5  2  0 -2]
 [-4 -5  1  3]] 


In [46]:
# Numpy Sum, Prod, Diff, and Statistics 
# Mean and Median 
np.random.seed(30)
x = np.random.randint(1, 10, (5, ))
w = np.array([1, 2, 3, 4,5])

print(f"w : \n{w}")
print(f"x : \n{x}")
print(np.average(x, weights=w))
print(np.sum(w*x)/np.sum(w))
 

w : 
[1 2 3 4 5]
x : 
[6 6 5 8 3]
5.333333333333333
5.333333333333333


In [52]:
import numpy as np 
vec_x = np.arange(9)
print(f"x : {vec_x}")
median1 = np.median(vec_x)
print(f"median1 : {median1}")

vec_y = np.arange(10)
print(f"y : {vec_y}")
median2 = np.median(vec_y)
print(f"median2 : {median2}")

x : [0 1 2 3 4 5 6 7 8]
median1 : 4.0
y : [0 1 2 3 4 5 6 7 8 9]
median2 : 4.5


In [58]:
import numpy as np 

np.random.seed(30)
vec_x = np.random.randint(1, 10, (100, ))
print(f"vec_x : {vec_x}")

mean = np.mean(vec_x)
median = np.median(vec_x)

print(f"mean : {mean}")
print(f"median : {median}")

vec_x = np.append(vec_x, 1000)
print(vec_x)

print(f"mean : {mean}")
print(f"median : {median}")

vec_x : [6 6 5 8 3 6 2 4 8 8 2 2 4 3 3 5 5 7 1 7 1 8 5 3 2 8 2 9 6 8 2 9 8 5 7 9 7
 1 8 6 4 2 5 3 4 9 1 8 2 5 3 2 8 7 1 8 1 4 7 8 4 4 6 8 5 8 4 7 8 3 4 3 8 4
 7 4 7 5 3 7 3 4 1 9 3 2 6 8 6 2 5 7 9 7 8 1 1 3 7 2]
mean : 5.04
median : 5.0
[   6    6    5    8    3    6    2    4    8    8    2    2    4    3
    3    5    5    7    1    7    1    8    5    3    2    8    2    9
    6    8    2    9    8    5    7    9    7    1    8    6    4    2
    5    3    4    9    1    8    2    5    3    2    8    7    1    8
    1    4    7    8    4    4    6    8    5    8    4    7    8    3
    4    3    8    4    7    4    7    5    3    7    3    4    1    9
    3    2    6    8    6    2    5    7    9    7    8    1    1    3
    7    2 1000]
mean : 5.04
median : 5.0


In [63]:
import numpy as np 

scores = np.random.normal(loc = 10, 
                          scale = 5, 
                          size = (100, ))

scores_var = np.var(scores)
scores_std = np.std(scores)

print(f"variance : {scores_var}")
print(f"standard deviation : {scores_std}")

print(f"square of std : {scores_std**2}")
print(f"square root of var : {scores_var**0.5}")

variance : 25.262979284288875
standard deviation : 5.026229131693945
square of std : 25.26297928428887
square root of var : 5.026229131693945


In [66]:
mean_vec = [50, 60, 70]
std_vec = [3, 5, 10]

num_studnet, num_class = 100, 3 

score_mat = np.random.normal(loc = mean_vec, 
                             scale = std_vec, 
                             size = (num_studnet, num_class))

print("shape of score_mat", score_mat.shape)
print("dtype of score_mat", score_mat.dtype)

means = score_mat.mean(axis = 0)
stds = score_mat.std(axis = 0)

print(means)
print(stds)

shape of score_mat (100, 3)
dtype of score_mat float64
[49.91768543 60.08708565 70.18389659]
[2.93472271 5.16183427 9.97603596]


In [80]:
# Max Values and Indices 
# numpy.amax 
# ndarray.max 
# numpy.argmax
# ndarray.argmax 

import numpy as np

np.random.seed(30)
print("\n==============Vector==============")
vec_a = np.random.randint(0, 10, (10, ))
# max_idx = np.argmax(vec_a)
print(f"vec_a : shape {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")
print(f"vec_a.max() : {vec_a.max()}")
print(f"np.amax() : {np.amax(vec_a)}")
print(f"values : {np.amax(vec_a)} index : {np.argmax(vec_a)}")
# Matrix 
print("\n==============Matrix==============")
mat_a = np.arange(45).reshape(5, 9)
print(f"mat_a : shape {mat_a.shape} ndim : {mat_a.ndim} \n {mat_a}")
print(f"mat_a.max() : {mat_a.max()}")
print(f"np.amax() : {np.amax(mat_a)}")
print(f"values : {np.amax(mat_a)} index : {np.argmax(mat_a)}")

# Tensor
print("\n==============Tensor==============")
ten_a = np.arange(45).reshape(3, 3, 5)
print(f"ten_a : shape {ten_a.shape} ndim : {ten_a.ndim} \n {ten_a}")
print(f"mat_a.max() : {ten_a.max()}")
print(f"np.amax() : {np.amax(ten_a)}")
print(f"values : {np.amax(ten_a)} index : {np.argmax(ten_a)}")
  


==============Vector==============
vec_a : shape (10,) ndim : 1 
 [5 5 4 7 2 5 1 3 9 7]
vec_a.max() : 9
np.amax() : 9
values : 9 index : 8

==============Matrix==============
mat_a : shape (5, 9) ndim : 2 
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]
mat_a.max() : 44
np.amax() : 44
values : 44 index : 44

==============Tensor==============
ten_a : shape (3, 3, 5) ndim : 3 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
mat_a.max() : 44
np.amax() : 44
values : 44 index : 44


In [88]:
import numpy as np 

means = [50, 60, 70]
stds = [3, 5, 10]
num_studnet, num_class = 100, 3

score_mat = np.random.normal(loc = means, 
                             scale = stds,
                             size = (num_studnet, num_class))

score_mat = score_mat.astype(np.float32)
score_max = np.max(score_mat, axis=0)
print(f"score_mat : shape {score_mat.shape } : ndim : {score_max.ndim} max : {score_max} \n{score_mat} ")
score_max_idx = np.argmax(score_mat, axis = 0)
print(f"max indices : , {np.argmax(score_mat)}")
score_max_idx = np.argmax(score_mat, axis=1)
print(f"max subject : \n{score_max_idx}")


score_mat : shape (100, 3) : ndim : 1 max : [56.348293 72.21124  94.85317 ] 
[[51.903378 53.787285 65.69364 ]
 [49.862015 59.152092 73.29327 ]
 [46.71372  61.66275  86.3583  ]
 [50.825993 59.80912  61.13009 ]
 [49.62005  57.412514 64.635666]
 [48.597263 63.842808 65.71596 ]
 [50.135715 52.836704 80.77834 ]
 [47.45449  60.798622 71.726036]
 [48.732815 61.750587 70.20547 ]
 [49.772133 61.887688 71.82553 ]
 [49.810318 60.23394  73.97926 ]
 [51.429913 55.73478  71.54861 ]
 [50.428715 59.443256 82.090454]
 [51.374454 62.193672 82.99482 ]
 [45.827156 55.289806 72.10672 ]
 [50.93425  71.60902  65.24935 ]
 [50.293167 57.371315 86.34064 ]
 [50.693024 62.453815 73.75387 ]
 [44.353176 51.085037 64.83973 ]
 [49.6981   60.062096 80.84855 ]
 [48.398052 51.898323 74.26015 ]
 [52.272697 56.900795 51.4355  ]
 [48.304165 47.81027  56.57663 ]
 [53.212093 61.422634 77.07531 ]
 [51.750866 61.572712 71.67899 ]
 [50.064266 56.975437 74.596825]
 [50.71205  53.560978 59.69439 ]
 [52.613197 67.69768  59.731586]

In [94]:
import numpy as np

# Maxinum and Minimum
np.random.seed(30)

print("\n==============Vector==============")
vec_a = np.random.randint(1, 10, (10, ))
vec_b = np.random.randint(1, 10, (10, ))

print(f"vec_a shape {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")
print(f"vec_b shape {vec_b.shape} ndim : {vec_b.ndim} \n {vec_b}")
maximum = np.maximum(vec_a, vec_b)
minimum = np.minimum(vec_a, vec_b)
print(f"maximum :\n {maximum}")
print(f"minimum :\n {minimum}")


print("\n==============Matrix==============")
mat_a = np.random.randint(1, 10, (3, 4))
mat_b = np.random.randint(1, 10, (3, 4))
print(f"mat_a shape {mat_a.shape} ndim : {mat_a.ndim} \n {mat_a}")
print(f"mat_b shape {mat_b.shape} ndim : {mat_b.ndim} \n {mat_b}")
maximum = np.maximum(mat_a, mat_b)
minimum = np.minimum(mat_a, mat_b)
print(f"maximum :\n {maximum}")
print(f"minimum :\n {minimum}")



==============Vector==============
vec_a shape (10,) ndim : 1 
 [6 6 5 8 3 6 2 4 8 8]
vec_b shape (10,) ndim : 1 
 [2 2 4 3 3 5 5 7 1 7]
maximum :
 [6 6 5 8 3 6 5 7 8 8]
minimum :
 [2 2 4 3 3 5 2 4 1 7]

==============Matrix==============
mat_a shape (3, 4) ndim : 2 
 [[1 8 5 3]
 [2 8 2 9]
 [6 8 2 9]]
mat_b shape (3, 4) ndim : 2 
 [[8 5 7 9]
 [7 1 8 6]
 [4 2 5 3]]
maximum :
 [[8 8 7 9]
 [7 8 8 9]
 [6 8 5 9]]
minimum :
 [[1 5 5 3]
 [2 1 2 6]
 [4 2 2 3]]


In [96]:
vec_a = np.random.randint(1, 10, (10, ))
vec_b = np.random.randint(1, 10, (10, ))

print(f"vec_a shape {vec_a.shape} ndim : {vec_a.ndim} \n {vec_a}")
print(f"vec_b shape {vec_b.shape} ndim : {vec_b.ndim} \n {vec_b}")

maximum = np.zeros_like(vec_a)
maximum[vec_a >= vec_b ] = vec_a[vec_a >= vec_b]
maximum[vec_a < vec_b ] = vec_b[vec_a < vec_b]

print(f"np.maxinum \n{np.maximum(vec_a, vec_b)}")
print(f"maximum \n {maximum}")

vec_a shape (10,) ndim : 1 
 [5 8 4 7 8 3 4 3 8 4]
vec_b shape (10,) ndim : 1 
 [7 4 7 5 3 7 3 4 1 9]
np.maxinum 
[7 8 7 7 8 7 4 4 8 9]
maximum 
 [7 8 7 7 8 7 4 4 8 9]


In [99]:
np.random.seed(30)
u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))

print(f"u shpae: {u.shape} ndim : {u.ndim}")
print(f"v shpae: {v.shape} ndim : {v.ndim}")

up_val = np.full_like(u, fill_value=100)
down_val = np.full_like(v, fill_value=-100)
print(np.where(u > v, up_val, down_val))


u shpae: (10,) ndim : 1
v shpae: (10,) ndim : 1
[-100  100  100  100 -100  100 -100 -100  100  100]


In [102]:
import numpy as np 

np.random.seed(30)
u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))

print(f"u shape : {u.shape} ndim {u.ndim} \n ")
print(f"v shape : {v.shape} ndim {v.ndim} \n ")

maximum = np.maximum(u, v)
maximum_where = np.where(u > v , u, v)
print(f"maximum {maximum.shape}\n{maximum}")
print(f"maximum(where) {maximum.shape}\n{maximum_where}")

u shape : (10,) ndim 1 
 
v shape : (10,) ndim 1 
 
maximum (10,)
[7 5 4 7 2 5 4 4 9 7]
maximum(where) (10,)
[7 5 4 7 2 5 4 4 9 7]
