In [22]:
import numpy as np 
# Changing ndarraus chages 

# ndarray.shape -> ndarray.reshape, ndarray.resize, ndarray.flatten, ndarray.raval 
# ndarray.itemsize -> ndarray.astype 

a_vec_np = np.arange(6)

b_mat_np = np.reshape(a_vec_np, (2, 3))
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_mat_np)

a_vec_np = np.arange(24)
b_ten_np = np.reshape(a_vec_np, (2, 3, 4))
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_ten_np)
print(b_ten_np[0][1][3])


print("\n\n")
a_vec_np = np.arange(6)
b_mat_np = a_vec_np.reshape(2, 3)
print("original ndarray: \n", a_vec_np)
print("reshaped ndarray: \n", b_mat_np)

a_vec_np = np.random.randint(0, 100, (100, ))
b_ten_np = a_vec_np.reshape(20, 5)
print(a_vec_np.reshape((20,5)).mean(axis=0).max())
print(np.max(np.reshape(a_vec_np, (20, 5)), axis=0))

original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]
original ndarray: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
7



original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]
60.05
[92 93 95 91 91]
